/* 2019-05-23 14:58:03 fangluo */
(function(){function k(b){"string"==typeof b&&(b=d.getElementById(b));return b}function s(b,v,a){u.addEventListener?b.addEventListener(v,a,!1):u.attachEvent&&b.attachEvent("on"+v,function(){a.call(b,u.event)})}function q(b,a){b.className.match(RegExp("(\\s|^)"+a+"(\\s|$)"))||(b.className+=" "+a)}function a(b,a){b.className=b.className.replace(RegExp("(\\s|^)"+a+"(\\s|$)")," ")}function f(b){if(!b.pageX&&b.clientX){var a=1,c=document.body;c.getBoundingClientRect&&(a=c.getBoundingClientRect(),a=(a.right-
a.left)/c.clientWidth);return{x:b.clientX/a+d.body.scrollLeft+d.documentElement.scrollLeft,y:b.clientY/a+d.body.scrollTop+d.documentElement.scrollTop}}return{x:b.pageX,y:b.pageY}}var d=document,u=window,t=function(){var b=d.createElement("div");return function(a){b.innerHTML=a;a=b.childNodes[0];b.removeChild(a);return a}}(),p=document.documentElement.getBoundingClientRect?function(b){var a=b.getBoundingClientRect(),c=b.ownerDocument;b=c.body;var c=c.documentElement,d=c.clientTop||b.clientTop||0,g=
c.clientLeft||b.clientLeft||0,l=1;b.getBoundingClientRect&&(l=b.getBoundingClientRect(),l=(l.right-l.left)/b.clientWidth);1<l&&(g=d=0);return{top:a.top/l+(window.pageYOffset||c&&c.scrollTop/l||b.scrollTop/l)-d,left:a.left/l+(window.pageXOffset||c&&c.scrollLeft/l||b.scrollLeft/l)-g}}:function(b){if(u.jQuery)return jQuery(b).offset();var a=0,c=0;do a+=b.offsetTop||0,c+=b.offsetLeft||0;while(b=b.offsetParent);return{left:c,top:a}},e=function(){var b=0;return function(){return"ValumsAjaxUpload"+b++}}(),
c=function(){var b;return function(){if(b)return b;if("undefined"!==typeof XMLHttpRequest)b=new XMLHttpRequest;else for(var a=["Microsoft.XmlHttp","MSXML2.XmlHttp.5.0","MSXML2.XmlHttp.4.0","MSXML2.XmlHttp.3.0","MSXML2.XmlHttp.2.0"],c=0;c<a.length;c++)try{b=new ActiveXObject(a[c]);break}catch(d){}return b}}();Ajax_upload=AjaxUpload=function(b,a){b.jquery?b=b[0]:"string"==typeof b&&/^#.*/.test(b)&&(b=b.slice(1));b=k(b);this._input=null;this._button=b;this._justClicked=this._submitting=this._disabled=
!1;this._parentDialog=d.body;this._type="ontouchstart"in document.documentElement;if(window.jQuery&&jQuery.ui&&jQuery.ui.dialog){var c=jQuery(this._button).parents(".ui-dialog");c.length&&(this._parentDialog=c[0])}this._settings={action:"upload.php",name:"userfile",data:{type:"journals",typeID:13,token:"78A566F2-AA8A-4C4C-8EE8-F99FB3D4A1D8",randomKey:+new Date},autoSubmit:!0,responseType:!1,closeConnection:"",hoverClass:"hover",onChange:function(g,b){},onSubmit:function(g,b){},onComplete:function(g,
b){}};for(var e in a)this._settings[e]=a[e];this._createInput();this._type||this._rerouteClicks()};AjaxUpload.prototype={setData:function(b){this._settings.data=b},disable:function(){this._disabled=!0},enable:function(){this._disabled=!1},destroy:function(){this._input&&(this._input.parentNode&&this._input.parentNode.removeChild(this._input),this._input=null)},_createInput:function(){var b=this,a=d.createElement("input");a.setAttribute("type","file");a.setAttribute("name",this._settings.name);var c=
{position:"absolute",margin:"-5px 0 0 -175px",padding:0,width:"220px",height:"30px",fontSize:"14px",opacity:0,cursor:"pointer",display:"none",zIndex:2147483583},e;for(e in c)a.style[e]=c[e];"0"!==a.style.opacity&&(a.style.filter="alpha(opacity=0)");this._parentDialog.appendChild(a);s(a,"change",function(){var g=this.value.replace(/.*(\/|\\)/,"");!1!=b._settings.onChange.call(b,g,/[.]/.exec(g)?/[^.]+$/.exec(g.toLowerCase()):"")&&b._settings.autoSubmit&&b.submit()});s(a,"click",function(){b.justClicked=
!0;setTimeout(function(){b.justClicked=!1},2500)});this._input=a;this._type&&this._pad()},_pad:function(){$(this._button).html($(this._input).attr("style","").css({opacity:0,width:"100%",height:"100%",display:"block",margin:"0 0 0 -20px"}))},_rerouteClicks:function(){var b,c,e,t,g=this,l={top:0,left:0},h=!1;s(g._button,"mouseover",function(a){if(g._input&&!h){h=!0;a=g._button;var x,A,f;A=p(a);x=A.left;f=A.top;A=x+a.offsetWidth;b=x;c=A;e=f;t=f+a.offsetHeight;g._parentDialog!=d.body&&(l=p(g._parentDialog))}});
s(document,"mousemove",function(w){var x=g._input;if(x&&h)if(g._disabled)a(g._button,g._settings.hoverClass),x.style.display="none";else if(w=f(w),w.x>=b&&w.x<=c&&w.y>=e&&w.y<=t)x.style.top=w.y-l.top+"px",x.style.left=w.x-l.left+"px",x.style.display="block",q(g._button,g._settings.hoverClass);else{h=!1;var d=setInterval(function(){g.justClicked||(h||(x.style.display="none"),clearInterval(d))},25);a(g._button,g._settings.hoverClass)}})},_createIframe:function(){var b=e(),a=t('<iframe src="javascript:false;" name="'+
b+'" />');a.id=b;a.style.display="none";d.body.appendChild(a);return a},submit:function(){var b=this,a=this._settings;if(""!==this._input.value){var t={name:this._input.value.replace(/.*(\/|\\)/,""),id:e()};if(!1!=a.onSubmit.call(this,t,/[.]/.exec(t.name)?/[^.]+$/.exec(t.name.toLowerCase()):"")){var p=this._createIframe(),g=this._createForm(p);g.appendChild(this._input);if(a.closeConnection&&/AppleWebKit|MSIE/.test(navigator.userAgent)){var l=c();l.open("GET",a.closeConnection,!1);l.send("")}g.submit();
d.body.removeChild(g);this._input=g=null;this._createInput();var h=!1;s(p,"load",function(g){if("javascript:'%3Chtml%3E%3C/html%3E';"==p.src||"javascript:'<html></html>';"==p.src)h&&setTimeout(function(){d.body.removeChild(p)},0);else if(g=p.contentDocument?p.contentDocument:frames[p.id].document,!g.readyState||"complete"==g.readyState)if(!g.body||"false"!=g.body.innerHTML){var l;g.XMLDocument?l=g.XMLDocument:g.body?(l=g.body.innerHTML,a.responseType&&"json"==a.responseType.toLowerCase()&&(g.body.firstChild&&
"PRE"==g.body.firstChild.nodeName.toUpperCase()&&(l=g.body.firstChild.firstChild.nodeValue),l=l?window.eval("("+l+")"):{})):l=g;a.onComplete.call(b,t,l);h=!0;p.src="javascript:'<html></html>';"}})}else d.body.removeChild(this._input),this._input=null,this._createInput()}},_createForm:function(b){var a=this._settings,c=t('<form method="post" enctype="multipart/form-data"></form>');c.style.display="none";c.action=a.action;c.target=b.name;d.body.appendChild(c);for(var e in a.data)b=d.createElement("input"),
b.type="hidden",b.name=e,b.value=a.data[e],c.appendChild(b);return c}}})();
(function(k,s){function q(){this.ajaxu={};this.type=this.checkflash().pv[0]?"swf":"ajax"}q.prototype.checkflash=function(){var a=window,f=document,d=navigator,f="undefined"!=typeof f.getElementById&&"undefined"!=typeof f.getElementsByTagName&&"undefined"!=typeof f.createElement,u=d.userAgent.toLowerCase(),t=d.platform.toLowerCase(),p=t?/win/.test(t):/win/.test(u),t=t?/mac/.test(t):/mac/.test(u),u=/webkit/.test(u)?parseFloat(u.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",c=[0,0,0],b=null;
if("undefined"!=typeof d.plugins&&"object"==typeof d.plugins["Shockwave Flash"])!(b=d.plugins["Shockwave Flash"].description)||"undefined"!=typeof d.mimeTypes&&d.mimeTypes["application/x-shockwave-flash"]&&!d.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(plugin=!0,e=!1,b=b.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),c[0]=parseInt(b.replace(/^(.*)\..*$/,"$1"),10),c[1]=parseInt(b.replace(/^.*\.(.*)\s.*$/,"$1"),10),c[2]=/[a-zA-Z]/.test(b)?parseInt(b.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!=
typeof a.ActiveXObject)try{var v=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");v&&(b=v.GetVariable("$version"))&&(e=!0,b=b.split(" ")[1].split(","),c=[parseInt(b[0],10),parseInt(b[1],10),parseInt(b[2],10)])}catch(k){}return{w3:f,pv:c,wk:u,ie:e,win:p,mac:t}};q.prototype.upload=function(a){if("swf"===this.type)this.ajaxu=new SWFUpload(a);else{document.domain=a.domain;var f=document.getElementById(a.button_placeholder_id);s("javascript:void(0)"+a.button_placeholder_id).css({width:a.button_width,height:a.button_height,
background:"url("+a.button_image_url+") 0 0 no-repeat"}).html("");this.ajaxu=new AjaxUpload(f,{action:a.upload_url,data:a.post_params,onSubmit:function(d,f){if(!f&&/^(jpg|jpeg|png)$/.test(f))return alert("\u65e0\u6548\u7684\u6587\u4ef6\u540d"),!1;a.file_queued_handler.call(this,d);return!0},onComplete:function(d,f){a.upload_success_handler.call(this,d,f)}})}return this.ajaxu};q.prototype.formatdata=function(a){a=(new Function("return "+a.replace(/(<script)+[^<>]*>[^\0]*(<\/script>)+/gm,"")))();return"undefined"!=
typeof a.error&&""==a.error?a.data[0]:""};window.gs_upload=q})(window,jQuery);
function ask_uplload_com(){function k(){"swf"==q.type&&$.browser.msie&&swfu.setButtonImageURL(u)}function s(a,d){var e=$(".upload_ul li").length;if(5<=e)$.gs_alert({text:'<p style="color:#066B9F">\u5bf9\u4e0d\u8d77\u6700\u591a\u53ea\u53ef\u4e0a\u4f205\u5f20\u7167\u7247\u3002</p>'});else{for(var e=a.name,c=0,c=e.replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx").length,b="",f=0,c=c-10;c<e.length&&!(128<e.charCodeAt(c)?f+=2:f++,b+=e.charAt(c),10<=f);c++);e=[];e.push('<li data-type="error" class="error">');
e.push(' <i class="failed"></i>');e.push(' <i class="delete"></i>');e.push(' <span class="error-msg">'+d+"</span>");e.push("</li>");e=$(e.join(""));$(".upload_ul").append(e);k();e=$(".upload_ul li").length;5<=e&&$(".btn_upload").css({"margin-left":"-10000px"})}}var q={},a;a=$("#gs_uploadurl").val();$("#imgRootPath").val();var f=!0,d=$.browser.msie?61:60,u=DETAIL_API.upload_btn_domain+"/ask2/img/btn_upload.png",q=new gs_upload;a={domain:a.replace(/(http:|https:)?\/\/.*?\.(.*?)\/.*/ig,"$2"),upload_url:a,
flash_url:function(a){re=/(.*\/)/ig;r=a.match(re);return r[0]+"images/swfupload_fp9.swf"}(a),file_types:"*.jpg;*.png;",file_size_limit:"10MB",file_queue_limit:5,button_placeholder_id:"uploadBtn",button_image_url:u,button_width:d,button_height:60,WINDOW_MODE:{WINDOW:"window",OPAQUE:"opaque"},debug:!1,prevent_swf_caching:!1,preserve_relative_urls:!1,button_action:SWFUpload.BUTTON_ACTION.SELECT_FILES,button_cursor:SWFUpload.CURSOR.HAND,button_disabled:!1,post_params:{typeID:13,type:"journals",token:"78A566F2-AA8A-4C4C-8EE8-F99FB3D4A1D8",
randomKey:(new Date).getTime()},file_queue_error_handler:function(a,d,e){try{switch($(".upload_ul").find("li[data-type='error']").remove(),f=!1,d){case SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED:$.gs_alert({text:'<p style="color:#066B9F">\u5bf9\u4e0d\u8d77\uff0c\u6700\u591a\u53ea\u53ef\u4e0a\u4f205\u5f20\u7167\u7247\u3002</p>'});break;case SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT:s(a,"\u56fe\u7247\u592a\u5927");break;case SWFUpload.QUEUE_ERROR.ZERO_BYTE_FILE:s(a,"\u4e0d\u80fd\u4e3a\u7a7a");break;
case SWFUpload.QUEUE_ERROR.INVALID_FILETYPE:s(a,"\u683c\u5f0f\u9519\u8bef")}}catch(c){this.debug(c)}},file_queued_handler:function(a){try{f&&$(".upload_ul").find("li[data-type='error']").remove();var d=a.id;if(5<=$(".upload_ul").find("li").length)$.gs_alert({text:'<p style="color:#066B9F">\u5bf9\u4e0d\u8d77\uff0c\u6700\u591a\u53ea\u53ef\u4e0a\u4f205\u5f20\u7167\u7247\u3002</p>'});else{var e=$("javascript:void(0)"+d);0===e.length&&(a=[],a.push('<li id="'+d+'">'),a.push(' <i class="delete"></i>'),"ajax"==q.type?a.push(' <span class="speed_load"></span>'):
a.push('<span class="speed-text">0%</span><canvas class="speed_canvas" width="50" height="50"></canvas>'),a.push("</li>"),e=$(a.join("")),$(".upload_ul").append(e));k()}}catch(c){this.debug(c)}},file_dialog_complete_handler:function(a,d){try{this.startUpload(),f=!0}catch(e){this.debug(e)}},upload_progress_handler:function(a,d,e){d=Math.ceil(100*(d/e));$(".upload_ul #"+a.id).find(".speed-text").text(d+"%");if(document.createElement("canvas").getContext&&0<$(".upload_ul #"+a.id).find(".speed_canvas").length){e=
function(a){return Math.PI/180*a-90*(Math.PI/180)};a=$(".upload_ul #"+a.id).find(".speed_canvas").get(0);var c=a.getContext("2d");c.clearRect(0,0,a.width,a.height);c.beginPath();c.strokeStyle="#D6D6D6";c.arc(25,25,20,e(0),e(360));c.lineWidth=2;c.stroke();c.beginPath();c.strokeStyle="#37C200";c.arc(25,25,20,e(0),e(3.6*d));c.lineWidth=2;c.stroke()}return d},upload_complete_handler:function(a){$(".upload_ul #"+a.id).find(".speed-text").text("\u5df2\u5b8c\u6210")},upload_success_handler:function(a,d){var e=
q.formatdata(d);$(".upload_ul #"+a.id).attr("data-img-id",e.data);e=(new Function("return "+d.replace(/(<script)+[^<>]*>[^\0]*(<\/script>)+/gm,"")))();"undefined"!=typeof e.error&&""==e.error?(url=e.data[0].thumbUrl,$field=$(".upload_ul #"+a.id),$field.find(".speed-text").remove(),$field.find(".speed_canvas").remove(),$field.find(".speed_load").remove(),$field.append('<span><img src="'+url+'"></span>')):$.gs_alert({text:"\u65e0\u6548\u7684\u6570\u636e"});5<=$(".upload_ul li").length&&$(".btn_upload").css({"margin-left":"-10000px"})}};
a=q.upload(a);$(".upload_ul").on("click","i.delete",function(){$(this).parent("li").remove();$(".btn_upload").css({"margin-left":"0"})});return{gsupload:q,askUploadFn:a}}
(function(k){var s={className:"autosizejs",append:"",callback:!1,resizeDelay:10},q="fontFamily fontSize fontWeight fontStyle letterSpacing textTransform wordSpacing textIndent".split(" "),a,f=k('<textarea tabindex="-1" style="position:absolute; top:-999px; left:0; right:auto; bottom:auto; border:0; padding: 0; -moz-box-sizing:content-box; -webkit-box-sizing:content-box; box-sizing:content-box; word-wrap:break-word; height:0 !important; min-height:0 !important; overflow:hidden; transition:none; -webkit-transition:none; -moz-transition:none;"/>').data("autosize",!0)[0];
f.style.lineHeight="99px";"99px"===k(f).css("lineHeight")&&q.push("lineHeight");f.style.lineHeight="";k.fn.autosize=function(d){if(!this.length)return this;d=k.extend({},s,d||{});f.parentNode!==document.body&&k(document.body).append(f);return this.each(function(){function u(){var a,g;"getComputedStyle"in window?(a=window.getComputedStyle(c,null),g=c.getBoundingClientRect().width,k.each(["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],function(b,l){g-=parseInt(a[l],10)}),f.style.width=
g+"px"):f.style.width=Math.max(b.width(),0)+"px"}function s(){var g={};a=c;f.className=d.className;v=parseInt(b.css("maxHeight"),10);k.each(q,function(a,l){g[l]=b.css(l)});k(f).css(g);u();if(window.chrome){var l=c.style.width;c.style.width="0px";c.style.width=l}}function p(){var b,l;a!==c?s():u();f.value=c.value+d.append;f.style.overflowY=c.style.overflowY;l=parseInt(c.style.height,10);f.scrollTop=0;f.scrollTop=9E4;b=f.scrollTop;v&&b>v?(c.style.overflowY="scroll",b=v):(c.style.overflowY="hidden",
b<y&&(b=y));b+=z;l!==b&&(c.style.height=b+"px",g&&d.callback.call(c,c))}function e(){clearTimeout(h);h=setTimeout(function(){var a=b.width();a!==w&&(w=a,p())},parseInt(d.resizeDelay,10))}var c=this,b=k(c),v,y,z=0,g=k.isFunction(d.callback),l={height:c.style.height,overflow:c.style.overflow,overflowY:c.style.overflowY,wordWrap:c.style.wordWrap,resize:c.style.resize},h,w=b.width();if(!b.data("autosize")){b.data("autosize",!0);if("border-box"===b.css("box-sizing")||"border-box"===b.css("-moz-box-sizing")||
"border-box"===b.css("-webkit-box-sizing"))z=b.outerHeight()-b.height();y=Math.max(parseInt(b.css("minHeight"),10)-z||0,b.height());b.css({overflow:"hidden",overflowY:"hidden",wordWrap:"break-word",resize:"none"===b.css("resize")||"vertical"===b.css("resize")?"none":"horizontal"});if("onpropertychange"in c)if("oninput"in c)b.on("input.autosize keyup.autosize",p);else b.on("propertychange.autosize",function(){"value"===event.propertyName&&p()});else b.on("input.autosize",p);if(!1!==d.resizeDelay)k(window).on("resize.autosize",
e);b.on("autosize.resize",p);b.on("autosize.resizeIncludeStyle",function(){a=null;p()});b.on("autosize.destroy",function(){a=null;clearTimeout(h);k(window).off("resize",e);b.off("autosize").off(".autosize").css(l).removeData("autosize")});p()}})}})(window.jQuery||window.$);"object"!==typeof JSON&&(JSON={});
(function(){function k(a){return 10>a?"0"+a:a}function s(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=t[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function q(a,c){var b,f,k,t,g=d,l,h=c[a];h&&("object"===typeof h&&"function"===typeof h.toJSON)&&(h=h.toJSON(a));"function"===typeof p&&(h=p.call(c,a,h));switch(typeof h){case "string":return s(h);case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);
case "object":if(!h)return"null";d+=u;l=[];if("[object Array]"===Object.prototype.toString.apply(h)){t=h.length;for(b=0;b<t;b+=1)l[b]=q(b,h)||"null";k=0===l.length?"[]":d?"[\n"+d+l.join(",\n"+d)+"\n"+g+"]":"["+l.join(",")+"]";d=g;return k}if(p&&"object"===typeof p)for(t=p.length,b=0;b<t;b+=1)"string"===typeof p[b]&&(f=p[b],(k=q(f,h))&&l.push(s(f)+(d?": ":":")+k));else for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(k=q(f,h))&&l.push(s(f)+(d?": ":":")+k);k=0===l.length?"{}":d?"{\n"+d+l.join(",\n"+
d)+"\n"+g+"}":"{"+l.join(",")+"}";d=g;return k}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+k(this.getUTCMonth()+1)+"-"+k(this.getUTCDate())+"T"+k(this.getUTCHours())+":"+k(this.getUTCMinutes())+":"+k(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var a,f,d,u,t,p;"function"!==typeof JSON.stringify&&(f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
t={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(a,c,b){var f;u=d="";if("number"===typeof b)for(f=0;f<b;f+=1)u+=" ";else"string"===typeof b&&(u=b);if((p=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return q("",{"":a})});"function"!==typeof JSON.parse&&(a=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,JSON.parse=function(d,
c){function b(a,d){var g,l,h=a[d];if(h&&"object"===typeof h)for(g in h)Object.prototype.hasOwnProperty.call(h,g)&&(l=b(h,g),void 0!==l?h[g]=l:delete h[g]);return c.call(a,d,h)}var f;d=String(d);a.lastIndex=0;a.test(d)&&(d=d.replace(a,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(d.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=
eval("("+d+")"),"function"===typeof c?b({"":f},""):f;throw new SyntaxError("JSON.parse");})})();var uplaodDOM={};
$(function(){function k(g){var b=$("#asktitle_sspop");u=setTimeout(function(){if(p[g]){a.offset();b.slideDown(300);b.find(".sspop_ajax").html("");var d="";for(i=0;i<p[g].length;i++)d=d+'<a class="cf" target="_blank" title="'+p[g][i].HighlighterTitle+'" href="'+p[g][i].AskLinkUrl+'"><span class="asktitle">'+p[g][i].AskTitle+'</span><span class="askcount">'+p[g][i].ReplyCount+"\u56de\u7b54</span></a>";b.find(".sspop_ajax").html(d)}else $.getJSON(ASKSEARCH_API.GetAskSearch+"&Jsoncallback=?",{Keyword:encodeURIComponent(g)},
function(d){if(void 0!=d){a.offset();b.slideDown(300);b.find(".sspop_ajax").html("");var c="";for(i=0;i<d.length;i++)c=c+'<a target="_blank" title="'+d[i].HighlighterTitle+'" href="'+d[i].AskLinkUrl+'"><span class="asktitle">'+d[i].AskTitle+'</span><span class="askcount">'+d[i].ReplyCount+"\u56de\u7b54</span></a>";b.find(".sspop_ajax").html(c);p[g]=[];p[g]=d}else b.find(".sspop_ajax").html(""),b.slideUp(300)})},200)}function s(a){var b="",c=$(".ask_tag").find(".asktag_show").length;for(i=0;i<c;i++)b+=
$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();t=setTimeout(function(){if(e[a]){5==e[a].length?d.hide():(d.fadeIn(300),d.placeholder());var c="";$(".ask_tag").find(".asktag_show").remove();for(i=0;i<e[a].length;i++)c=c+"<span class='asktag_show' data-relation='"+e[a][i].RelationType+"' data-relatedinfolist='"+JSON.stringify(e[a][i].RelatedInfoList[0])+"'><b class='asktagtext'><span>"+e[a][i].TagName+"</span><a class='delasktag' href='javascript:;'></a></b></span>";$(".ask_tag").prepend(c);
var c=[],h="",f=$(".ask_tag").find(".asktag_show").length;for(i=0;i<f;i++)c[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text(),h+=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();b!=h&&GetAskInviteList({askTagNamesPost:c})}else $.getJSON(DETAIL_API.GetAskTagsByTitle+"&Jsoncallback=?",{Keyword:encodeURIComponent(a)},function(c){if(void 0!=c){5==c.length?d.hide():(d.fadeIn(300),d.placeholder());var h="";$(".ask_tag").find(".asktag_show").remove();for(i=
0;i<c.length;i++)h=h+"<span class='asktag_show' data-relation='"+c[i].RelationType+"' data-relatedinfolist='"+JSON.stringify(c[i].RelatedInfoList[0])+"'><b class='asktagtext'><span>"+c[i].TagName+"</span><a class='delasktag' href='javascript:;'></a></b></span>";$(".ask_tag").prepend(h);$(".ask_tag").parent(".form_block").next(".error_line").html("");$(".ask_tag").removeClass("errorinput");e[a]=[];e[a]=c}else $(".ask_tag").find(".asktag_show").remove(),d.fadeIn(300),d.placeholder();c=[];var h="",f=
$(".ask_tag").find(".asktag_show").length;for(i=0;i<f;i++)c[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text(),h+=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();b!=h&&GetAskInviteList({askTagNamesPost:c})})},200)}function q(a){var b=$("#addinvite_pop");y=setTimeout(function(){if(z[a]){b.html("");var c="";for(i=0;i<data.length;i++)c=c+'<a class="invite_block cf" title="'+data[i].UserDisplayName+'" href="javascript:;" data-userlink="'+data[i].UserHomePageUrl+
'"><img class="invite_img" src="'+data[i].UserHeadPhotoUrl+'" ><p>'+data[i].UserDisplayName+"</p><p>"+data[i].FormatShortDistrictMaster+"</p>";b.html(c);c=$("#addinvite_input").offset();b.css({top:c.top+23,left:c.left}).fadeIn(300)}else $.getJSON(DETAIL_API.AskSearchInvite+"&Jsoncallback=?",{Keyword:encodeURIComponent(a)},function(a){if(void 0!=a){var g=$.trim(g);b.html("");var c="";for(i=0;i<a.length;i++)c=c+'<a class="invite_block cf" title="'+a[i].UserDisplayName+'" href="javascript:;" data-userlink="'+
a[i].UserHomePageUrl+'" data-username="'+a[i].UserDisplayName+'" data-userPhotourl="'+a[i].UserHeadPhotoUrl+'" data-userinfo="'+a[i].FormatShortDistrictMaster+'" data-userid="'+a[i].UserId+'"><img class="invite_img" src="'+a[i].UserHeadPhotoUrl+'" ><p class="invite_name">'+a[i].UserDisplayName+'</p><p class="invite_info">'+a[i].FormatShortDistrictMaster+"</p>";b.html(c);c=$("#addinvite_input").offset();b.css({top:c.top+23,left:c.left}).fadeIn(300);z[g]=[];z[g]=a}else b.html("")})},200)}uplaodDOM=
ask_uplload_com();var a=$("#asktitle_input"),f=$("#askinfo_area"),d=$(".addtag_input");qeventsAddinput(".addtag_input",15);d.placeholder();a.after('<div id="asktitle_sspop" class="asktitle_sspop"><p class="sspop_p">\u4f60\u7684\u95ee\u9898\u53ef\u80fd\u5df2\u7ecf\u6709\u4e86\u7b54\u6848\uff1a</p><div class="sspop_ajax"></div><div class="cf sspop_bline"><a target="_blank" class="sspop_blink" href="javascript:;">\u641c\u7d22\u66f4\u591a\u5173\u4e8e\u201c<b></b>\u201d<i class="icon_rightarrow"></i></a></div></div>');
a.placeholder();var u=0,t=0,p={},e={},c={},b=function(a){$.post(DETAIL_API.SearchAskLog,{askid:a.attr("href").match(/\/(\d+)/)[1],content:encodeURIComponent($.trim($("#asktitle_input").val()))})};$("#asktitle_sspop").on("click",".sspop_ajax a",function(){b($(this))});var v=a.val().replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx"),v=Math.ceil(v.length/2);clearTimeout(t);s(a.val());a.focus(function(){$(this).addClass("focusinput");a.removeClass("errorinput");a.parent(".form_block").next(".error_line").html("");
var b=$("#asktitle_sspop");$(this);if(b.is(":hidden")){var c=$(this).val(),d=c.replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx");10<=Math.ceil(d.length/2)?(d=ASKSEARCH_API.AskSiteLink+"?keywords="+encodeURIComponent(c),b.find(".sspop_blink").find("b").html(c),b.find(".sspop_blink").attr("title","\u641c\u7d22\u66f4\u591a\u5173\u4e8e\u201c"+c+"\u201d"),b.find(".sspop_blink").attr({href:d}),clearTimeout(u),k(c)):b.slideUp(300)}}).keyup(function(a){GS.xssFilter($(this).val());var c=$("#asktitle_sspop");
$(this);var d=$(this).val(),f=d.replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx");if(10<=Math.ceil(f.length/2))switch(a.keyCode){case 40:c.find(".sspop_ajax").find(".current").index()==c.find(".sspop_ajax").find("a").length-1?(a=c.find(".current"),a.removeClass("current"),c.find(".sspop_ajax").find("a").eq(0).addClass("current")):0<c.find(".current").length?(a=c.find(".current"),a.next("a").addClass("current"),a.removeClass("current")):c.find(".sspop_ajax").find("a").eq(0).addClass("current");break;
case 38:c.find(".current").hasClass("sspop_blink")?(a=c.find(".current"),c.find("a").eq(c.find(".sspop_ajax").find("a").length-1).addClass("current"),a.removeClass("current")):0==c.find(".current").index()?c.find(".current").removeClass("current"):0<c.find(".current").length&&(a=c.find(".current"),a.prev("a").addClass("current"),a.removeClass("current"));break;case 13:if(0<c.find(".current").length)a=c.find(".current").attr("href"),b(c.find(".current")),window.location.href=a;else return!1;break;
case 27:c.slideUp(300);break;default:a=ASKSEARCH_API.AskSiteLink+"?keywords="+encodeURIComponent(d),c.find(".sspop_blink").find("b").text(d),c.find(".sspop_blink").attr("title","\u641c\u7d22\u66f4\u591a\u5173\u4e8e\u201c"+d+"\u201d"),c.find(".sspop_blink").attr({href:a}),clearTimeout(u),k(d)}else clearTimeout(u),c.slideUp(300);clearTimeout(t);s(d)});qeventsNum("#asktitle_input",50,".asktitle_numcount b");f.placeholder();f.focus(function(){$(this).parent(".askarea_con").addClass("focusinput").removeClass("errorinput");
$(this).parents(".form_block").next(".error_line").html("")}).blur(function(){$(this).parent(".askarea_con").removeClass("focusinput")});f.autosize();qeventsNum("#askinfo_area",1E3,".askarea_numcount b");var y=0;$("body").append('<div id="addtag_sspop" class="addtag_sspop"><a class="taginput" href="javascript:;" data-relation="0"></a><div class="addtagpop_ajax"></div></div>');d.keyup(function(a){function b(){y=setTimeout(function(){if(c[f]){e.find(".addtagpop_ajax").html("");var a="";for(i=0;i<c[f].length;i++)a=
a+"<a title='"+c[f][i].TagName+"' href='javascript:;' data-relation='"+c[f][i].RelationType+"'  data-relatedinfolist='"+JSON.stringify(c[f][i].RelatedInfoList[0])+"'>"+c[f][i].TagName+"</a>",c[f][i].TagName==f&&$("#addtag_sspop .taginput").hide();e.find(".addtagpop_ajax").html(a)}else $.getJSON(DETAIL_API.GetAskTagsByAdd+"&Jsoncallback=?",{Keyword:encodeURIComponent(f)},function(a){if(void 0!=a){f=$.trim(f);e.find(".addtagpop_ajax").html("");var b="";for(i=0;i<a.length;i++)b=b+"<a title='"+a[i].TagName+
"' href='javascript:;'  data-relation='"+a[i].RelationType+"'  data-relatedinfolist='"+JSON.stringify(a[i].RelatedInfoList[0])+"'>"+a[i].TagName+"</a>",a[i].TagName==f&&$("#addtag_sspop .taginput").hide();e.find(".addtagpop_ajax").html(b);c[f]=[];c[f]=a}else e.find(".addtagpop_ajax").html("")})},200)}GS.xssFilter($(this).val());var h=$(this),f=$(this).val(),e=$("#addtag_sspop");if(f)switch(a.keyCode){case 40:0<e.find(".current").length?(a=e.find(".current"),a.hasClass("taginput")?e.find(".addtagpop_ajax").find("a").eq(0).addClass("current"):
a.next("a").addClass("current"),a.removeClass("current")):!0==e.find(".taginput").is(":visible")?e.find(".taginput").addClass("current"):e.find(".addtagpop_ajax").find("a").eq(0).addClass("current");break;case 38:e.find(".current").hasClass("taginput")?e.find(".current").removeClass("current"):0==e.find(".current").index()?(a=e.find(".current"),e.find(".taginput").addClass("current"),a.removeClass("current")):0<e.find(".current").length&&(a=e.find(".current"),a.prev("a").addClass("current"),a.removeClass("current"));
break;case 13:if(0<e.find(".current").length){var k=$.trim(e.find(".current").text());a=e.find(".current").attr("data-relation");var p=h.siblings(".asktag_show").length;for(i=0;i<p;i++)if(h.siblings(".asktag_show").eq(i).text()==k)return $.gs_alert({text:'<p style="color:#333;">\u4e0d\u80fd\u6dfb\u52a0\u76f8\u540c\u6807\u7b7e</p>'}),e.find(".addtagpop_ajax").html(""),e.hide(),!1;h.before('<span class="asktag_show" data-relation="'+a+'"><b class="asktagtext"><span>'+k+'</span><a class="delasktag" href="javascript:;"></a></b></span>');
a=e.find(".current").attr("data-relatedinfolist");p=h.siblings(".asktag_show").length;if("undefined"!=a&&5>p){var q=!0;a=JSON.parse(a);for(m=0;m<p;m++)$(".ask_tag").find(".asktag_show").eq(m).find("span").html()==a.TagName&&(q=!1);q&&d.before('<span class="asktag_show sport_asktag" data-relation="'+a.RelationType+'" data-relatedinfolist="undefined"><b class="asktagtext"><span>'+a.TagName+'</span><a class="delasktag" href="javascript:;"></a></b></span>')}}else if($.trim(h.val())){k=$.trim(h.val());
k=k.replace(/\s+/g," ");k=k.replace("<","&lt;").replace(">","&gt;");p=h.siblings(".asktag_show").length;for(i=0;i<p;i++)if(h.siblings(".asktag_show").eq(i).find("span").html()==k)return $.gs_alert({text:'<p style="color:#333;">\u4e0d\u80fd\u6dfb\u52a0\u76f8\u540c\u6807\u7b7e</p>'}),e.find(".addtagpop_ajax").html(""),e.hide(),!1;$.getJSON(DETAIL_API.GetAskTagsByAdd+"&Jsoncallback=?",{Keyword:encodeURIComponent(k)},function(a){if(void 0!=a){var b=!1,c="";for(i=0;i<a.length;i++)if(a[i].TagName==k){c=
c+'<span class="asktag_show" href="javascript:;"  data-relation="'+a[i].RelationType+'"><b class="asktagtext"><span>'+a[i].TagName+'</span><a class="delasktag" href="javascript:;"></a></b></span>';h.before(c);a=JSON.stringify(a[i].RelatedInfoList[0]);p=h.siblings(".asktag_show").length;if("undefined"!=a&&5>p){b=!0;a=JSON.parse(a);for(m=0;m<p;m++)$(".ask_tag").find(".asktag_show").eq(m).find("span").html()==a.TagName&&(b=!1);b&&d.before('<span class="asktag_show sport_asktag" data-relation="'+a.RelationType+
'" data-relatedinfolist="undefined"><b class="asktagtext"><span>'+a.TagName+'</span><a class="delasktag" href="javascript:;"></a></b></span>')}b=!0;break}b||(a='<span class="asktag_show" data-relation="0" data-relatedinfolist="undefined"><b class="asktagtext"><span>'+k+'</span><a class="delasktag" href="javascript:;"></a></b></span>',h.before(a))}else a='<span class="asktag_show" data-relation="0" data-relatedinfolist="undefined"><b class="asktagtext"><span>'+k+'</span><a class="delasktag" href="javascript:;"></a></b></span>',
h.before(a)})}h.val("");e.find(".addtagpop_ajax").html("");e.hide();$(".ask_tag").removeClass("errorinput");$(".ask_tag").parent(".form_block").next(".error_line").html("");setTimeout(function(){var a=[],b=$(".ask_tag").find(".asktag_show").length;4<b&&h.hide();for(i=0;i<b;i++)a[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();GetAskInviteList({askTagNamesPost:a})},100);AddInputHide();break;case 27:h.val("");e.hide();break;default:clearTimeout(y),$("#addtag_sspop .taginput").show(),
$.trim(h.val())&&(b(),a=$.trim(f),a=a.replace(/\s+/g," "),e.find(".taginput").text(a),a=h.offset(),e.css({top:a.top+23,left:a.left}).fadeIn(300)),AddInputHide()}else clearTimeout(y),e.hide()}).focus(function(){$(this).addClass("addtag_inputfocus")}).blur(function(){$("#addtag_sspop").is(":hidden")&&$(this).removeClass("addtag_inputfocus")});$("#addtag_sspop").on("click","a",function(){var a=$("#addtag_sspop"),b=$(this).text(),b=b.replace("<","&lt;").replace(">","&gt;"),c=$(this).attr("data-relation"),
e=$(".ask_tag").find(".asktag_show").length;for(i=0;i<e;i++)if($(".ask_tag").find(".asktag_show").eq(i).text()==b)return $.gs_alert({text:'<p style="color:#333;">\u4e0d\u80fd\u6dfb\u52a0\u76f8\u540c\u6807\u7b7e</p>'}),a.find(".addtagpop_ajax").html(""),a.hide(),!1;d.before('<span class="asktag_show" data-relation="'+c+'"><b class="asktagtext"><span>'+b+'</span><a class="delasktag" href="javascript:;"></a></b></span>');e=$(".ask_tag").find(".asktag_show").length;b=$(this).attr("data-relatedinfolist");
if("undefined"!=b&&void 0!=b&&5>e){c=!0;b=JSON.parse(b);for(m=0;m<e;m++)$(".ask_tag").find(".asktag_show").eq(m).find("span").html()==b.TagName&&(c=!1);c&&d.before('<span class="asktag_show sport_asktag" data-relation="'+b.RelationType+'" data-relatedinfolist="undefined"><b class="asktagtext"><span>'+b.TagName+'</span><a class="delasktag" href="javascript:;"></a></b></span>')}d.val("");d.placeholder();a.find(".addtagpop_ajax").html("");a.hide();$(".ask_tag").parent(".form_block").next(".error_line").html("");
$(".ask_tag").removeClass("errorinput");d.removeClass("addtag_inputfocus");e=$(".ask_tag").find(".asktag_show").length;4<e&&d.hide();setTimeout(function(){var a=[],b=$(".ask_tag").find(".asktag_show").length;for(i=0;i<b;i++)a[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();GetAskInviteList({askTagNamesPost:a})},100)});$(".ask_form").on("click",".delasktag",function(){$(this).parent().parent().remove();AddInputHide();var a=!0,b=$(".ask_tag").find(".asktag_show").length;
for(j=0;j<b;j++)"undefined"!=$(".ask_tag").find(".asktag_show").eq(j).attr("data-relatedinfolist")&&(a=!1);setTimeout(function(){a&&$(".ask_tag").find(".sport_asktag").remove();var c=[];b=$(".ask_tag").find(".asktag_show").length;for(i=0;i<b;i++)c[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();GetAskInviteList({askTagNamesPost:c})},100)});$(".upload_ul").on("mouseenter","li",function(){$(this).find(".delete").show()}).on("mouseleave","li",function(){$(this).find(".delete").hide()});
var z={};$("body").append('<div id="addinvite_pop" class="addinvite_pop"></div>');$("#addinvite_input").placeholder();$("#addinvite_input").keyup(function(a){0<=$(this).val().indexOf("<script>")&&$(this).val($(this).val().replace(/<script>/g,"\uff1cscript\uff1e"));$(this);a=$(this).val();var b=$("#addinvite_pop");a?(clearTimeout(0),$.trim(a)&&q(a)):(clearTimeout(0),b.hide())}).focus(function(){$(this).addClass("addinvite_inputfocus");var a=$(this).val();clearTimeout(0);$.trim(a)&&q(a)}).blur(function(){$("#addinvite_pop").is(":hidden")&&
$(this).removeClass("addinvite_inputfocus")});$("#addinvite_pop").on("click",".invite_block",function(){var a=$(".invite_con .invite_list").find("li").length;for(i=0;i<a;i++)if($(this).attr("data-userid")==$(".invite_con .invite_list").find("li").eq(i).attr("data-userid"))return $.gs_alert({text:'<p style="color:#333;">\u5df2\u9080\u8bf7\u8be5\u7528\u6237</p>'}),!1;a='<li class="cf" data-userid="'+$(this).attr("data-userid")+'"><a class="invite_img" href="'+$(this).attr("data-userlink")+'" target="_blank"><img src="'+
$(this).attr("data-userPhotourl")+'" alt=""></a><p class="invite_name"><a href="'+$(this).attr("data-userlink")+'" target="_blank">'+$(this).attr("data-username")+'</a></p><p class="invite_place">'+$(this).attr("data-userinfo")+'</p><div class="invite_btnline"><span class="icon_invited">\u5df2\u9080\u8bf7</span><a class="deleteinvite" href="javascript:;">\u53d6\u6d88</a></div></li>';$(".invite_con .invite_list").prepend(a);$("#addinvite_pop").html("");$("#addinvite_pop").hide();$("#addinvite_input").removeClass("addinvite_inputfocus");
a=$(".invite_con .invite_list").find("li").length;$(".invite_search span b").html(a);9==a&&$(".invite_con .invite_search").slideUp(200)});$(".invite_con").on("click",".deleteinvite",function(){$(this).parents("li").attr("data-userid")==$("#InviteUserId").val()&&$("#InviteUserId").val("0");$(this).parents("li").addClass("invite_hide").delay(100).fadeOut(500,function(){$(this).remove();var a=$(".invite_con .invite_list").find("li").length;$(".invite_search span b").html(a)});$(".invite_con .invite_search").slideDown(200)});
$("#submit_askbtn").click(function(){if(0==$(this).data("isOne")&&!$(this).hasClass("a_popup_login"))if("swf"==uplaodDOM.gsupload.type&&uplaodDOM.askUploadFn.getStats())if(0<uplaodDOM.askUploadFn.getStats().files_queued)$.gs_alert({text:'<p style="color:#333;">\u8bf7\u7b49\u5f85\u56fe\u7247\u4e0a\u4f20\u5b8c\u6210</p>'});else{var b=a.val().replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx"),b=Math.ceil(b.length/2),c=!1,d=$(".ask_tag").find(".asktag_show").length;for(m=0;m<d;m++)if("6"==$(".ask_tag").find(".asktag_show").eq(m).attr("data-relation")||
"11"==$(".ask_tag").find(".asktag_show").eq(m).attr("data-relation")){c=!0;break}$(".upload_ul").find("li.error").remove();var e=function(){var a=$(".askpage_content h1").offset().top;$("html,body").animate({scrollTop:a},600)};if(!a.val()||"\u6e05\u6670\u5177\u4f53\u7684\u95ee\u9898 \uff0c\u4f1a\u6709\u52a9\u4e8e\u4f60\u83b7\u5f97\u6ee1\u610f\u7684\u89e3\u7b54\u3002"==a.val()||""==$.trim(a.val())||10>b||0==$(".ask_tag").find(".asktag_show").length||!c)return a.val()&&"\u6e05\u6670\u5177\u4f53\u7684\u95ee\u9898 \uff0c\u4f1a\u6709\u52a9\u4e8e\u4f60\u83b7\u5f97\u6ee1\u610f\u7684\u89e3\u7b54\u3002"!=
a.val()&&""!=$.trim(a.val())||(a.parent(".form_block").next(".error_line").html("\u8bf7\u586b\u597d\u6807\u9898\u518d\u53d1\u8868\u54e6").show(),a.removeClass("focusinput").addClass("errorinput")),10>b&&(a.parent(".form_block").next(".error_line").html("\u6807\u9898\u4e0d\u5f97\u5c11\u4e8e10\u4e2a\u5b57").show(),a.removeClass("focusinput ").addClass("errorinput")),0==$(".ask_tag").find(".asktag_show").length&&($(".ask_tag").parent(".form_block").next(".error_line").html("\u95ee\u9898\u5fc5\u987b\u5173\u8054\u81f3\u5c11\u4e00\u4e2a\u76ee\u7684\u5730/\u666f\u70b9\u6807\u7b7e").show(),
$(".ask_tag").addClass("errorinput")),c||($(".ask_tag").parent(".form_block").next(".error_line").html("\u95ee\u9898\u5fc5\u987b\u5173\u8054\u81f3\u5c11\u4e00\u4e2a\u76ee\u7684\u5730/\u666f\u70b9\u6807\u7b7e").show(),$(".ask_tag").addClass("errorinput")),e(),!1;$(this).gsdisable({time:15E3,text:"<i></i>\u53d1\u8868\u4e2d",callback:function(){}});b=a.val();c=f.val();"\u5982\u95ee\u9898\u6807\u9898\u65e0\u6cd5\u8be6\u7ec6\u9610\u8ff0\u4f60\u7684\u95ee\u9898\uff0c\u4f60\u53ef\u4ee5\u5728\u6b64\u8865\u5145\u3002"==
c&&(c="");e=[];for(i=0;i<d;i++)e[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();var d=[],k=$(".upload_ul li").length;if(0<k)for(n=0;n<k;n++)d[n]=$(".upload_ul li").eq(n).attr("data-img-id");var k=[],p=$(".invite_list li").length;for(n=0;n<p;n++)k[n]=$(".invite_list li").eq(n).attr("data-userid");submitAsk({askTitle:b,askContent:c,askTagNames:e,askPicId:d,InviteUserIds:k})}else{b=a.val().replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx");b=Math.ceil(b.length/2);c=!1;d=$(".ask_tag").find(".asktag_show").length;
for(m=0;m<d;m++)if("6"==$(".ask_tag").find(".asktag_show").eq(m).attr("data-relation")||"11"==$(".ask_tag").find(".asktag_show").eq(m).attr("data-relation")){c=!0;break}$(".upload_ul").find("li.error").remove();e=function(){var a=$(".askpage_content h1").offset().top;$("html,body").animate({scrollTop:a},600)};if(!a.val()||"\u6e05\u6670\u5177\u4f53\u7684\u95ee\u9898 \uff0c\u4f1a\u6709\u52a9\u4e8e\u4f60\u83b7\u5f97\u6ee1\u610f\u7684\u89e3\u7b54\u3002"==a.val()||""==$.trim(a.val())||10>b||0==$(".ask_tag").find(".asktag_show").length||
!c)return a.val()&&"\u6e05\u6670\u5177\u4f53\u7684\u95ee\u9898 \uff0c\u4f1a\u6709\u52a9\u4e8e\u4f60\u83b7\u5f97\u6ee1\u610f\u7684\u89e3\u7b54\u3002"!=a.val()&&""!=$.trim(a.val())||(a.parent(".form_block").next(".error_line").html("\u8bf7\u586b\u597d\u6807\u9898\u518d\u53d1\u8868\u54e6").show(),a.removeClass("focusinput").addClass("errorinput")),10>b&&(a.parent(".form_block").next(".error_line").html("\u6807\u9898\u4e0d\u5f97\u5c11\u4e8e10\u4e2a\u5b57").show(),a.removeClass("focusinput ").addClass("errorinput")),
0==$(".ask_tag").find(".asktag_show").length&&($(".ask_tag").parent(".form_block").next(".error_line").html("\u95ee\u9898\u5fc5\u987b\u5173\u8054\u81f3\u5c11\u4e00\u4e2a\u76ee\u7684\u5730/\u666f\u70b9\u6807\u7b7e").show(),$(".ask_tag").addClass("errorinput")),c||($(".ask_tag").parent(".form_block").next(".error_line").html("\u95ee\u9898\u5fc5\u987b\u5173\u8054\u81f3\u5c11\u4e00\u4e2a\u76ee\u7684\u5730/\u666f\u70b9\u6807\u7b7e").show(),$(".ask_tag").addClass("errorinput")),e(),!1;$(this).gsdisable({time:15E3,
text:"<i></i>\u53d1\u8868\u4e2d",callback:function(){}});b=a.val();c=f.val();"\u5982\u95ee\u9898\u6807\u9898\u65e0\u6cd5\u8be6\u7ec6\u9610\u8ff0\u4f60\u7684\u95ee\u9898\uff0c\u4f60\u53ef\u4ee5\u5728\u6b64\u8865\u5145\u3002"==c&&(c="");e=[];for(i=0;i<d;i++)e[i]=$(".ask_tag").find(".asktag_show").eq(i).find(".asktagtext span").text();d=[];k=$(".upload_ul li").length;if(0<k)for(n=0;n<k;n++)d[n]=$(".upload_ul li").eq(n).attr("data-img-id");k=[];p=$(".invite_list li").length;for(n=0;n<p;n++)k[n]=$(".invite_list li").eq(n).attr("data-userid");
submitAsk({askTitle:b,askContent:c,askTagNames:e,askPicId:d,InviteUserIds:k})}});$(document).click(function(b){b=b?b:window.event;b=b.srcElement||b.target;var c=$(b).attr("class");"asktitle_sspop"==c||"ask_input focusinput"==c||"asktitle_sspop"==$(b).parents().attr("class")?(a.addClass("focusinput"),$(".addtag_sspop").hide(),$(".addinvite_pop").hide(),$(".addtag_input").removeClass("addtag_inputfocus"),$(".addinvite_input").removeClass("addinvite_inputfocus")):"addtag_sspop"==c||"addtag_input addtag_inputfocus"==
c||"addtag_sspop"==$(b).parents().attr("class")?($(".addinvite_pop").hide(),$(".addinvite_input").removeClass("addinvite_inputfocus")):"addinvite_pop"==c||"addinvite_input addinvite_inputfocus"==c||"addinvite_pop"==$(b).parents().attr("class")?($(".addtag_sspop").hide(),$(".addtag_input").removeClass("addtag_inputfocus")):($(".addtag_sspop").hide(),$(".addinvite_pop").hide(),$(".asktitle_sspop").slideUp(300),$(".addtag_input").removeClass("addtag_inputfocus"),$(".addinvite_input").removeClass("addinvite_inputfocus"),
a.removeClass("focusinput"))});$("#askerror_pop .btn_backedti,#askerror_pop .close").click(function(){$("#submit_askbtn").removeClass("gsn-btn-8").addClass("btn_askcommit btncommon_orange").html("\u53d1\u5e03\u95ee\u9898");$("#submit_askbtn").data("isOne",0)})});
function qeventsNum(k,s,q){var a=$(k),f=$(q);a.gsInputLen(function(d){if(d>=s)d=a.val(),d=$.gsSubstring(d,s,1),a.val(d),f.html(s);else{if(a.hasClass("ask_input")&&"\u6e05\u6670\u5177\u4f53\u7684\u95ee\u9898 \uff0c\u4f1a\u6709\u52a9\u4e8e\u4f60\u83b7\u5f97\u6ee1\u610f\u7684\u89e3\u7b54\u3002"==a.val()||a.hasClass("ask_text")&&"\u5982\u95ee\u9898\u6807\u9898\u65e0\u6cd5\u8be6\u7ec6\u9610\u8ff0\u4f60\u7684\u95ee\u9898\uff0c\u4f60\u53ef\u4ee5\u5728\u6b64\u8865\u5145\u3002"==a.val())return!1;f.html(d)}})}
function qeventsAddinput(k,s){var q=$(k);q.gsInputLen(function(a){-1>=s-a&&(a=q.val(),a=$.gsSubstring(a,s,1),q.val(a))})}function AddInputHide(){4<$(".ask_tag").find(".asktag_show").length?($(".addtag_input").hide(),$("#addtag_sspop").find(".addtagpop_ajax").html("")):$(".addtag_input").fadeIn(300)};
