/**
 * Ctrip JavaScript Code
 * http://www.ctrip.com/
 * Copyright(C) 2008 - 2014, Ctrip All rights reserved.
 * Version: 140919
 * Date: 2014-09-19
 */
;window.replace=function(){return ''};!function(t){function i(i,e){i.setAttribute("autocomplete","off"),this.$node=t(i),this.init(e)}var e={name:"emailPrompt",version:"1.0",init:function(){},uninit:function(){},module:i},s=document,n={css:".emailPrompt{padding:1px;}.emailPrompt .hover {background-color:#ccc;}.emailPrompt li {line-height:1.6; cursor:pointer; padding:3px}",style:"border: 1px solid #CCC; position: absolute; background-color: #FFF; min-width: 178px; +width: 178px; visibility: hidden",postfix:"sina.com 163.com 126.com qq.com sina.cn hotmail.com gmail.com sohu.com yahoo.com 139.com 189.com yeah.net",offset:[1,0],iframeDiff:0,listeners:{onHide:function(){}}};
    i.prototype={init:function(t){this.conf=this.setConf(t),this.listeners=this.conf.listeners,this._preprocess(),this._bindEvent()},setConf:function(i){return t.extend(!0,{},n,i||{})},_preprocess:function(){this.pos=[],this.index=0,this._convertList(),this._getPos(),this._createHTML(),this._setPos()},_convertList:function(){var t=this.conf.postfix;
            this.emails=("string"==typeof t?t.split(" "):t)},_getPos:function(){var t=this.$node.offset(),i=this.conf.offset;this.pos[0]=t.bottom+i[0],this.pos[1]=t.left+i[1]},_setPos:function(){var i=this.pos;t(this.box).css({top:i[0]+"px",left:i[1]+"px"})},_setHeight:function(){var i=this.pos,e=t(this.ul),s=t(e.find("li").get(0)),n=e.offset(),h=0,o=s.offset().height;
            this.ul_height=n.height;var c=this._getDomInfo();c.height<i[0]+n.height&&(h=c.height-i[0]-this.conf.iframeDiff-5,this.ul_height=Math.floor(h/o)*o,e.css({height:this.ul_height+"px","overflow-y":"scroll"}))},_createHTML:function(){var i,e,n;this.box=i=s.createElement("div"),this.ul=e=s.createElement("ul"),this.uid=i.id=t(i).uid(),e.className="emailPrompt",n=this._createCSS(),i.innerHTML=n,i.appendChild(e),this._initStyle(),t("container").append(i)
        },_getDomInfo:function(){var t={};return t=(window.frameElement&&"IFRAME"==window.frameElement.tagName?window.frameElement.getBoundingClientRect():document.body.getBoundingClientRect()),{width:t.width||t.right-t.left,height:t.height||t.bottom-t.top}},_initStyle:function(){this.box.style.cssText=this.conf.style
        },_createCSS:function(){var i=this.conf.css;return i=this._uniqueCSS(i),i="<style>"+i+"</style>",i=(t.browser.isIE?this._fixIECSS(i):i)},_uniqueCSS:function(t){var i,e=this.uid;return i=t.replace((/(\s*)([^\{\}]+)\{/g),function(t,i,s){return i+s.replace((/([^,]+)/g),"#"+e+" $1")+"{"})},_fixIECSS:function(t){return'<pre style="display:none;">fixIE</pre>'+t
        },_bindEvent:function(){var i=this.$node,e=t(this.ul);i.bind("focus",this._checkValue.bind(this)),i.bind(["keyup","keydown"],function(t){this._checkInput(t)}.bind(this)),e.bind("click",function(t){this._setInputValue(t)}.bind(this)),e.bind("mouseover",function(t){this._hoverState(t)}.bind(this)),t(s).bind("click",function(t){this._blurInput(t)
        }.bind(this))},_checkValue:function(){var t,i,e=this.$node.value();t=(i=e.indexOf("@"))&&-1!==i,(t?this._setList(e):this.hide())},_setList:function(t){var i,e=t.split("@");i=this._createList(e[0],e[1]),(""!==i?(this.ul.innerHTML=i,this.show(),this._changeClass(0)):this.hide())},_createList:function(t,i){for(var e,s=this.emails,n=0,h=0,o=s.length,c="";o>n;n++)e=s[n],0===e.indexOf(i)&&e!==i&&(c+="<li>"+t+"@"+e+"</li>",h++);
            return this.max=h-1,c},_hoverState:function(i){if("LI"===i.target.tagName.toUpperCase()){var e=t(this.ul).find("li").indexOf(i.target);this._changeClass(e),this.index=e}},_checkInput:function(t){var i=t.keyCode,e=t.type;("keyup"===e?this._checkKeyUp(i):this._checkKeyDown(t,i))},_checkKeyUp:function(t){var i=t>=48&&57>=t||t>=96&&105>=t,e=t>=65&&90>=t,s=106===t||t>=186&&192>=t||t>=219&&222>=t,n=i||e||s,h=8===t||46===t,o=27===t,c=13===t||108===t;
            (n||h)&&this._checkValue(),this.showState&&(c&&this._setInputValue(),o&&this.hide())},_checkKeyDown:function(t,i){var e=38===i||40===i,s=9===i,n=13===i||108===i;this.showState&&e&&(this._keyUpAndDown(i),t.preventDefault()),this.showState&&s&&this.hide(),n&&this.showState&&(t.preventDefault(),t.stopPropagation())
        },_keyUpAndDown:function(t){(38===t?this._keyUp():this._keyDown())},_keyUp:function(){this.index=(this.index<=0?this.max:this.index-1),this._scroll(this.index),this._changeClass(this.index)},_keyDown:function(){this.index=(this.index>=this.max?0:this.index+1),this._scroll(this.index),this._changeClass(this.index)
        },_changeClass:function(i){var e=t(this.ul).find("li"),s=t(e.get(i));e.removeClass("hover"),s[0].className="hover"},_scroll:function(i){var e=t(this.ul).find("li"),s=t(e.get(i)),n=t(this.ul).offset(),h=s.offset();(this.ul_height<h.top-n.top+h.height||h.top-n.top<=0)&&(this.ul.scrollTop=this.ul.scrollTop+h.top-n.top-this.ul_height+h.height)
        },_setInputValue:function(){this._writeValue(t(this.ul).find("li").get(this.index).innerHTML)},_writeValue:function(t){this.$node.value(t),this.hide()},_blurInput:function(t){var i=t.target;i!==this.ul&&i!==this.$node[0]&&this.hide()},show:function(){this._getPos(),this._setPos(),t(this.box).css("visibility","visible"),this._setHeight(),this.showState=!0
        },hide:function(){this.showState&&(t(this.box).css("visibility","hidden"),this.showState=!1,this.index=0,this.listeners.onHide.call(this,this.$node.value()))}},t.mod.reg(e)}(cQuery);