/* 2015-06-17 14:28:03 fangluo */
var CryptoJS=CryptoJS||function(b,a){var c={},d=c.lib={},l=function(){},n=d.Base={extend:function(a){l.prototype=this;var b=new l;a&&b.mixIn(a);b.hasOwnProperty("init")||(b.init=function(){b.$super.init.apply(this,arguments)});b.init.prototype=b;b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.init.prototype.extend(this)}},
m=d.WordArray=n.extend({init:function(b,c){b=this.words=b||[];this.sigBytes=c!=a?c:4*b.length},toString:function(a){return(a||q).stringify(this)},concat:function(a){var b=this.words,c=a.words,d=this.sigBytes;a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-8*(e%4)&255)<<24-8*((d+e)%4);else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.sigBytes+=a;return this},clamp:function(){var a=this.words,c=this.sigBytes;a[c>>>2]&=4294967295<<
32-8*(c%4);a.length=b.ceil(c/4)},clone:function(){var a=n.clone.call(this);a.words=this.words.slice(0);return a},random:function(a){for(var c=[],d=0;d<a;d+=4)c.push(4294967296*b.random()|0);return new m.init(c,a)}}),p=c.enc={},q=p.Hex={stringify:function(a){var b=a.words;a=a.sigBytes;for(var c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-8*(d%4)&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,
2),16)<<24-4*(d%8);return new m.init(c,b/2)}},e=p.Latin1={stringify:function(a){var b=a.words;a=a.sigBytes;for(var c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-8*(d%4)&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-8*(d%4);return new m.init(c,b)}},r=p.Utf8={stringify:function(a){try{return decodeURIComponent(escape(e.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return e.parse(unescape(encodeURIComponent(a)))}},
u=d.BufferedBlockAlgorithm=n.extend({reset:function(){this._data=new m.init;this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=r.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var c=this._data,d=c.words,e=c.sigBytes,u=this.blockSize,l=e/(4*u),l=a?b.ceil(l):b.max((l|0)-this._minBufferSize,0);a=l*u;e=b.min(4*a,e);if(a){for(var t=0;t<a;t+=u)this._doProcessBlock(d,t);t=d.splice(0,a);c.sigBytes-=e}return new m.init(t,e)},clone:function(){var a=n.clone.call(this);
a._data=this._data.clone();return a},_minBufferSize:0});d.Hasher=u.extend({cfg:n.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){u.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);return this._doFinalize()},blockSize:16,_createHelper:function(a){return function(b,c){return(new a.init(c)).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return(new t.HMAC.init(a,
c)).finalize(b)}}});var t=c.algo={};return c}(Math);
(function(b){function a(a,b,c,d,e,l,m){a=a+(b&c|~b&d)+e+m;return(a<<l|a>>>32-l)+b}function c(a,b,c,d,e,l,m){a=a+(b&d|c&~d)+e+m;return(a<<l|a>>>32-l)+b}function d(a,b,c,d,e,l,m){a=a+(b^c^d)+e+m;return(a<<l|a>>>32-l)+b}function l(a,b,c,d,e,l,m){a=a+(c^(b|~d))+e+m;return(a<<l|a>>>32-l)+b}for(var n=CryptoJS,m=n.lib,p=m.WordArray,q=m.Hasher,m=n.algo,e=[],r=0;64>r;r++)e[r]=4294967296*b.abs(b.sin(r+1))|0;m=m.MD5=q.extend({_doReset:function(){this._hash=new p.init([1732584193,4023233417,2562383102,271733878])},
_doProcessBlock:function(b,m){for(var n=0;16>n;n++){var p=m+n,s=b[p];b[p]=(s<<8|s>>>24)&16711935|(s<<24|s>>>8)&4278255360}var n=this._hash.words,p=b[m+0],s=b[m+1],q=b[m+2],r=b[m+3],v=b[m+4],w=b[m+5],x=b[m+6],y=b[m+7],z=b[m+8],A=b[m+9],B=b[m+10],C=b[m+11],D=b[m+12],E=b[m+13],F=b[m+14],G=b[m+15],f=n[0],g=n[1],h=n[2],k=n[3],f=a(f,g,h,k,p,7,e[0]),k=a(k,f,g,h,s,12,e[1]),h=a(h,k,f,g,q,17,e[2]),g=a(g,h,k,f,r,22,e[3]),f=a(f,g,h,k,v,7,e[4]),k=a(k,f,g,h,w,12,e[5]),h=a(h,k,f,g,x,17,e[6]),g=a(g,h,k,f,y,22,e[7]),
f=a(f,g,h,k,z,7,e[8]),k=a(k,f,g,h,A,12,e[9]),h=a(h,k,f,g,B,17,e[10]),g=a(g,h,k,f,C,22,e[11]),f=a(f,g,h,k,D,7,e[12]),k=a(k,f,g,h,E,12,e[13]),h=a(h,k,f,g,F,17,e[14]),g=a(g,h,k,f,G,22,e[15]),f=c(f,g,h,k,s,5,e[16]),k=c(k,f,g,h,x,9,e[17]),h=c(h,k,f,g,C,14,e[18]),g=c(g,h,k,f,p,20,e[19]),f=c(f,g,h,k,w,5,e[20]),k=c(k,f,g,h,B,9,e[21]),h=c(h,k,f,g,G,14,e[22]),g=c(g,h,k,f,v,20,e[23]),f=c(f,g,h,k,A,5,e[24]),k=c(k,f,g,h,F,9,e[25]),h=c(h,k,f,g,r,14,e[26]),g=c(g,h,k,f,z,20,e[27]),f=c(f,g,h,k,E,5,e[28]),k=c(k,f,
g,h,q,9,e[29]),h=c(h,k,f,g,y,14,e[30]),g=c(g,h,k,f,D,20,e[31]),f=d(f,g,h,k,w,4,e[32]),k=d(k,f,g,h,z,11,e[33]),h=d(h,k,f,g,C,16,e[34]),g=d(g,h,k,f,F,23,e[35]),f=d(f,g,h,k,s,4,e[36]),k=d(k,f,g,h,v,11,e[37]),h=d(h,k,f,g,y,16,e[38]),g=d(g,h,k,f,B,23,e[39]),f=d(f,g,h,k,E,4,e[40]),k=d(k,f,g,h,p,11,e[41]),h=d(h,k,f,g,r,16,e[42]),g=d(g,h,k,f,x,23,e[43]),f=d(f,g,h,k,A,4,e[44]),k=d(k,f,g,h,D,11,e[45]),h=d(h,k,f,g,G,16,e[46]),g=d(g,h,k,f,q,23,e[47]),f=l(f,g,h,k,p,6,e[48]),k=l(k,f,g,h,y,10,e[49]),h=l(h,k,f,g,
F,15,e[50]),g=l(g,h,k,f,w,21,e[51]),f=l(f,g,h,k,D,6,e[52]),k=l(k,f,g,h,r,10,e[53]),h=l(h,k,f,g,B,15,e[54]),g=l(g,h,k,f,s,21,e[55]),f=l(f,g,h,k,z,6,e[56]),k=l(k,f,g,h,G,10,e[57]),h=l(h,k,f,g,x,15,e[58]),g=l(g,h,k,f,E,21,e[59]),f=l(f,g,h,k,v,6,e[60]),k=l(k,f,g,h,C,10,e[61]),h=l(h,k,f,g,q,15,e[62]),g=l(g,h,k,f,A,21,e[63]);n[0]=n[0]+f|0;n[1]=n[1]+g|0;n[2]=n[2]+h|0;n[3]=n[3]+k|0},_doFinalize:function(){var a=this._data,c=a.words,d=8*this._nDataBytes,e=8*a.sigBytes;c[e>>>5]|=128<<24-e%32;var l=b.floor(d/
4294967296);c[(e+64>>>9<<4)+15]=(l<<8|l>>>24)&16711935|(l<<24|l>>>8)&4278255360;c[(e+64>>>9<<4)+14]=(d<<8|d>>>24)&16711935|(d<<24|d>>>8)&4278255360;a.sigBytes=4*(c.length+1);this._process();a=this._hash;c=a.words;for(d=0;4>d;d++)e=c[d],c[d]=(e<<8|e>>>24)&16711935|(e<<24|e>>>8)&4278255360;return a},clone:function(){var a=q.clone.call(this);a._hash=this._hash.clone();return a}});n.MD5=q._createHelper(m);n.HmacMD5=q._createHmacHelper(m)})(Math);
(function(b){b.fn.lpShowTipMod=function(a){a=b.extend({left:0,top:0,width:250,isBindEvent:!1,attachEvent:"mouseover",close:"\u77e5\u9053\u4e86"},a);return this.each(function(){var c=b(this),d=this,l=c.offset(),n=a.txt||c.attr("mod-data")||"",m,p=b("<div/>",{"class":"lp-newvison-tips",html:'<i></i><div class="bd"><div>'+n+'</div><div class="close close-b"><a href="javascript:;">'+a.close+"</a></div></div>"}).css({left:l.left+a.left,top:l.top+a.top,width:a.width+"px"});this.bind=function(){c[a.attachEvent](function(){clearTimeout(m);
"none"===p.css("display")?p.show().css({top:c.offset().top+a.top}):p.css({top:c.offset().top+a.top}).appendTo("body")});c.mouseout(function(){clearTimeout(m);d.hide()});p.mouseover(function(){clearTimeout(m)}).mouseout(function(){clearTimeout(m);d.hide()})};this.hide=function(){m=setTimeout(function(){p.hide()},200)};a.isBindEvent?d.bind():p.appendTo("body");"function"===typeof a.callback&&a.callback.call(p);this.inte=void 0})}})(jQuery);var strP='<div class="popUp"></div>',popUp,timeOut=null;
function showMail(b){window.clearTimeout(timeOut);popUp=jQuery(strP);var a=Math.max(document.body.scrollWidth,document.documentElement.scrollWidth),c=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight),d=jQuery(window).height(),l=jQuery(window).width(),n=b.height(),m=b.width(),c=Math.max(d,c);popUp.css({width:a+"px",height:c+"px",opacity:0.5}).appendTo("body").show();var p="0",a=window.location.href.replace("members","_m_e_m").replace("?","$").replace("&","^");jQuery.ajax({url:"/members/Ajax/CheckUserProfile.ashx?type=message"+
a,type:"GET",async:!1,dataType:"text",timeout:1E3,error:function(a){return!1},success:function(a){if("-1"==a)return alert("\u8bf7\u5148\u767b\u9646"),p="0",jQuery(".popUp").remove(),!1;p="0"==a?"1":a}});"1"==p?b.css({top:d/2-n/2+"px",left:l/2-m/2+"px"}).show().find("div.reback_email_show,.message-title").css("display","").end().find("div.reback_mask_comfirm").css("display","none"):"0"!=p&&(jQuery("div.reback_email_show,.message-title").css("display","none"),jQuery("div.reback_btn").remove(),jQuery(".lv").remove(),
b.css({top:d/2-n/2+"px",left:l/2-m/2+"px"}).show().find(".close_btn").after("<p class='lv'>\u53d1\u8868\u7559\u8a00\u9700\u8981\u6fc0\u6d3b\u4f60\u7684\u643a\u7a0b\u65c5\u884c\uff0c<a href=\""+p+'">\u7acb\u523b\u6fc0\u6d3b</a></p>'));b.bind("click",function(a){switch(jQuery(a.target).attr("mod")){case "rep":jQuery(".reback_email_show,.message-title").hide();jQuery(".reback_mask_comfirm").show();timeOut=setTimeout(function(){popUp.remove();jQuery(".reback_mask_comfirm").parent().hide()},5E3);break;
case "close":jQuery(".close_btn").parent().hide(),popUp.remove(),document.getElementById("title")&&(document.getElementById("title").value=""),document.getElementById("content")&&(document.getElementById("content").value=""),document.getElementById("backtitle")&&(document.getElementById("backtitle").value=""),document.getElementById("backcontent")&&(document.getElementById("backcontent").value="")}})}
jQuery(function(){jQuery("#write_email_btn").bind("click",function(){document.getElementById("receivererror").innerHTML="";document.getElementById("titleerror").innerHTML="";document.getElementById("contenterror").innerHTML="";showMail(jQuery("#write_infor"))})});
jQuery(function(){jQuery("#reback_email_btn").bind("click",function(){document.getElementById("inputReplyID").value=jQuery(this).attr("nowID");document.getElementById("backtitleerror").innerHTML="";document.getElementById("backcontenterror").innerHTML="";document.getElementById("senderName").innerHTML=document.getElementById("senderName").innerHTML;document.getElementById("backtitle").value="\u56de\u590d\uff1a"+$.trim(document.getElementById("title").innerHTML);showMail(jQuery("#reback_infor"))})});
function sendMessage(b){var a=0;document.getElementById("receivererror").innerHTML="";document.getElementById("titleerror").innerHTML="";document.getElementById("contenterror").innerHTML="";if(""==document.getElementById("receiver").value||"\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0"==document.getElementById("receiver").value)document.getElementById("receivererror").innerHTML="\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0",document.getElementById("receiver").focus(),"\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0"==
document.getElementById("receiver").value&&(document.getElementById("receiver").value=""),a=1;""==document.getElementById("title").value&&(document.getElementById("titleerror").innerHTML="\u8bf7\u5199\u6807\u9898",0==a&&document.getElementById("title").focus(),a=1);50<document.getElementById("title").value.length&&(document.getElementById("titleerror").innerHTML="\u6807\u9898\u4e0d\u53ef\u8d85\u8fc750\u5b57",0==a&&document.getElementById("title").focus(),a=1);""==document.getElementById("content").value&&
(document.getElementById("contenterror").innerHTML="\u8bf7\u5199\u7559\u8a00\u5185\u5bb9",document.getElementById("conplaceholder").style.display="none",0==a&&document.getElementById("content").focus(),a=1);200<document.getElementById("content").value.length&&(document.getElementById("contenterror").innerHTML="\u8f93\u5165\u5185\u5bb9\u957f\u5ea6\u8d85\u8fc7\u5b57\u6570\u9650\u5236\uff0c\u8bf7\u91cd\u65b0\u53d1\u9001",document.getElementById("conplaceholder").style.display="none",0==a&&document.getElementById("content").focus(),
a=1);0==a&&(a="",""==document.getElementById("getMaskName").value?a=document.getElementById("receiver").value:""!=document.getElementById("getMaskName").value&&(a=document.getElementById("getMaskName").value),a={receiver:escape(a),title:escape(document.getElementById("title").value),content:escape(document.getElementById("content").value)},jQuery.ajax({type:"get",url:"/members/Ajax/SendWebMessage.ashx",dateType:"plain",data:a,success:function(a){"-100"==a?window.location.href="/members/CheckEmail.aspx?PreUrl="+
window.location.href:"noreceiver"==a?(document.getElementById("receivererror").innerHTML="\u6635\u79f0\u6709\u8bef",document.getElementById("receiver").focus()):(a="success",document.getElementById("sendtitle").innerHTML=document.getElementById("title").value,document.getElementById("sendreceiver").innerHTML=document.getElementById("receiver").value,jQuery(".reback_email_show,.message-title").hide(300),jQuery(".reback_mask_comfirm").show(300),timeOut=setTimeout(function(){popUp.remove();jQuery(".reback_mask_comfirm").parent().hide(300,
function(){jQuery(".reback_mask_comfirm").parent().hide(300)})},5E3),"noconfirm"==b&&(document.getElementById("receiver").value="\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0"),document.getElementById("title").value="",document.getElementById("content").value="")}}))}
function changeIFrame(b,a){"send"==b?(jQuery(document.getElementById("sendlink")).parent().addClass("current"),jQuery(document.getElementById("receivelink")).parent().removeClass(),document.getElementById("messageiframe").src="sendlist.aspx?profileurlno="+a):(jQuery(document.getElementById("receivelink")).parent().addClass("current"),jQuery(document.getElementById("sendlink")).parent().removeClass(),document.getElementById("messageiframe").src="receivelist.aspx?profileurlno="+a)}
function checkall(){for(var b=1;20>=b;b++)document.getElementById("checkbox"+b)&&(document.getElementById("checkbox"+b).checked=!0);document.getElementById("checkall").style.display="none";document.getElementById("checkno").style.display="inline-block"}
function checkno(){for(var b=1;20>=b;b++)document.getElementById("checkbox"+b)&&(document.getElementById("checkbox"+b).checked=!1);document.getElementById("checkno").style.display="none";document.getElementById("checkall").style.display="inline-block"}
function deleteAllCheck(){for(var b=1;20>=b;b++)if(document.getElementById("checkbox"+b)&&!0==document.getElementById("checkbox"+b).checked)return!0;alert("\u8bf7\u9009\u62e9\u8981\u5220\u9664\u7684\u7559\u8a00");document.getElementById("checkbox1")&&document.getElementById("checkbox1").focus();return!1}
function backMessage(){var b=0;document.getElementById("backtitleerror").innerHTML="";document.getElementById("backcontenterror").innerHTML="";""==document.getElementById("backtitle").value&&(document.getElementById("backtitleerror").innerHTML="\u8bf7\u5199\u6807\u9898",0==b&&document.getElementById("backtitle").focus(),b=1);50<document.getElementById("backtitle").value.length&&(document.getElementById("backtitleerror").innerHTML="\u6807\u9898\u4e0d\u53ef\u8d85\u8fc750\u5b57",0==b&&document.getElementById("backtitle").focus(),
b=1);""==document.getElementById("backcontent").value&&(document.getElementById("backcontenterror").innerHTML="\u8bf7\u5199\u7559\u8a00\u5185\u5bb9",0==b&&document.getElementById("backcontent").focus(),b=1);500<document.getElementById("backcontent").value.length&&(document.getElementById("backcontenterror").innerHTML="\u7559\u8a00\u5185\u5bb9\u4e0d\u53ef\u8d85\u8fc7500\u5b57",0==b&&document.getElementById("backcontent").focus(),b=1);0==b&&(b=document.getElementById("receiverid").value,b={receiverid:escape(b),
title:escape(document.getElementById("backtitle").value),replyID:document.getElementById("inputReplyID").value,content:escape(document.getElementById("backcontent").value)},jQuery.ajax({type:"post",url:"/members/Ajax/SendWebMessageNew.ashx",dateType:"plain",data:b,success:function(a){"-100"==a?window.location.href="/members/CheckEmail.aspx?PreUrl="+window.location.href:"noreceiver"==a?alert("\u6ca1\u6709\u627e\u5230\u8be5\u7528\u6237\uff0c\u8bf7\u786e\u8ba4\u8f93\u5165\u7684\u5185\u5bb9"):"success"==
a?(document.getElementById("showbacktitle").innerHTML=document.getElementById("backtitle").value,document.getElementById("showsendername").innerHTML=document.getElementById("senderName").innerHTML,jQuery(".reback_email_show,.message-title").hide(300),jQuery(".reback_mask_comfirm").show(300),timeOut=setTimeout(function(){popUp.remove();jQuery(".reback_mask_comfirm").parent().hide(300,function(){jQuery(".reback_mask_comfirm").parent().hide(300)})},5E3),document.getElementById("backtitle").value="",
document.getElementById("backcontent").value=""):(document.getElementById("backresult").innerHTML="<h6>\u7559\u8a00\u53d1\u9001\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u9875\u9762\u540e\u91cd\u65b0\u63d0\u4ea4\u3002</h6>",jQuery(".reback_email_show,.message-title").hide(300),jQuery(".reback_mask_comfirm").show(300),timeOut=setTimeout(function(){popUp.remove();jQuery(".reback_mask_comfirm").parent().hide(300,function(){jQuery(".reback_mask_comfirm").parent().hide(300)})},5E3))}}))}
function $tabs(b,a){$(b).click(function(){$(this).addClass("current").siblings().removeClass();$(a).hide().eq($(b).index(this)).show()})}
function sendMessageNew(b){var a=0;document.getElementById("receivererror").innerHTML="";document.getElementById("titleerror").innerHTML="";document.getElementById("contenterror").innerHTML="";if(""==document.getElementById("receiver").value||"\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0"==document.getElementById("receiver").value)document.getElementById("receivererror").innerHTML="\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0",document.getElementById("receiver").focus(),"\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0"==
document.getElementById("receiver").value&&(document.getElementById("receiver").value=""),a=1;""==document.getElementById("receiverid").value&&(document.getElementById("receivererror").innerHTML="\u83b7\u53d6\u6536\u4ef6\u4eba\u4fe1\u606f\u5931\u8d25");""==document.getElementById("title").value&&(document.getElementById("titleerror").innerHTML="\u8bf7\u5199\u6807\u9898",0==a&&document.getElementById("title").focus(),a=1);50<document.getElementById("title").value.length&&(document.getElementById("titleerror").innerHTML=
"\u6807\u9898\u4e0d\u53ef\u8d85\u8fc750\u5b57",0==a&&document.getElementById("title").focus(),a=1);""==document.getElementById("content").value&&(document.getElementById("contenterror").innerHTML="\u8bf7\u5199\u7559\u8a00\u5185\u5bb9",document.getElementById("conplaceholder").style.display="none",0==a&&document.getElementById("content").focus(),a=1);200<document.getElementById("content").value.length&&(document.getElementById("contenterror").innerHTML="\u8f93\u5165\u5185\u5bb9\u957f\u5ea6\u8d85\u8fc7\u5b57\u6570\u9650\u5236\uff0c\u8bf7\u91cd\u65b0\u53d1\u9001",
document.getElementById("conplaceholder").style.display="none",0==a&&document.getElementById("content").focus(),a=1);0==a&&(a=document.getElementById("receiverid").value,a={receiverid:escape(a),title:escape(document.getElementById("title").value),content:escape(document.getElementById("content").value)},jQuery.ajax({type:"post",url:"/members/Ajax/SendWebMessageNew.ashx",dateType:"plain",data:a,success:function(a){"-100"==a?window.location.href="/members/CheckEmail.aspx?PreUrl="+window.location.href:
"noreceiver"==a?(document.getElementById("receivererror").innerHTML="\u6635\u79f0\u6709\u8bef",document.getElementById("receiver").focus()):"success"==a?(document.getElementById("sendtitle").innerHTML=document.getElementById("title").value,document.getElementById("sendreceiver").innerHTML=document.getElementById("receiver").value,jQuery(".reback_email_show,.message-title").hide(300),jQuery(".reback_mask_comfirm").show(300),timeOut=timeOut=setTimeout(function(){popUp.remove();jQuery(".reback_mask_comfirm").parent().hide(300,
function(){jQuery(".reback_mask_comfirm").parent().hide(300)})},5E3),"noconfirm"==b&&(document.getElementById("receiver").value="\u8bf7\u586b\u5199\u6536\u4ef6\u4eba\u6635\u79f0"),document.getElementById("title").value="",document.getElementById("content").value=""):(document.getElementById("sendresult").innerHTML="<h6>\u7559\u8a00\u53d1\u9001\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u9875\u9762\u540e\u91cd\u65b0\u63d0\u4ea4\u3002</h6>",jQuery(".reback_email_show").hide(300),jQuery(".reback_mask_comfirm,.message-title").show(300),
timeOut=setTimeout(function(){popUp.remove();jQuery(".reback_mask_comfirm").parent().hide(300,function(){jQuery(".reback_mask_comfirm").parent().hide(300)})},5E3))}}))}var isFUserRegister="";function showMore(){document.getElementById("emailmore").style.display="none";for(var b=1;5>=b;b++)document.getElementById("emailmore"+b).style.display="block"}
function openLetterShow(){document.getElementById("emaildetailerror").innerHTML="";if(""==document.getElementById("emaildetail").value)return document.getElementById("emaildetailerror").innerHTML="\u8bf7\u8f93\u5165\u9080\u8bf7\u9644\u8a00",document.getElementById("emaildetail").focus(),!1;window.open("/members/friends/invite_preview.aspx","","status=no,menubar=no,top=100,left=300,width=500,height=450,resizable=yes,scrollbars=yes")}
function checkLen(){0==document.getElementById("emaildetail").value.length?document.getElementById("emaildetailerror").innerHTML="\u8bf7\u8f93\u5165\u9080\u8bf7\u9644\u8a00":50<document.getElementById("emaildetail").value.length?document.getElementById("emaildetailerror").innerHTML="\u6700\u591a50\u5b57":document.getElementById("emaildetailerror").innerHTML="";return!1}function goBack(){window.history.back(-1)}
function goToIndex(b){jQuery(function(){var a;jQuery("#btnCancel").bind("click",function(c){a=a||jQuery('<div class="clue_uplayer"><div class="close_layerClue"></div><ul><li>\u786e\u8ba4\u53d6\u6d88\uff1f</li><li><input name="" id="btnNO" type="button" value="\u5426" /><input name="" id="btnYes" type="button" value="\u662f" /></li></ul></div>');a.css({display:"none",left:jQuery(c.target).offset().left-10+"px",top:jQuery(c.target).offset().top+15+"px"}).appendTo("body").slideDown(250).find("#btnYes").bind("click",
function(){window.location.href="/members/friends/invite.aspx?profileurlno="+b}).end().find("#btnNO").bind("click",function(){a.slideUp(function(){a.remove()})})})})}
jQuery(function(){var b;jQuery("#cancel-payatt").bind("click",function(a){var c=jQuery(a.target),d=c.offset(),l=jQuery(a.target).attr("profileurlno"),n=jQuery(a.target).attr("sessionprofileurlno");b=b||jQuery('<div class="clue_uplayer"><div class="close_layerClue"></div><ul><li>\u786e\u8ba4\u53d6\u6d88\uff1f</li><li><input name="" id="btnNO" type="button" value="\u5426" /><input name="" id="btnYes" type="button" value="\u662f" /></li></ul></div>');b.css({display:"none",left:d.left+3+"px",top:d.top+
18+"px"}).appendTo("body").show().find("#btnYes").bind("click",function(){c.html("\u8bf7\u7a0d\u7b49...");jQuery.ajax({type:"GET",url:"/members/Ajax/CancelFriend.ashx",dateType:"plain",data:{profileurlno:l,sessionprofileurlno:n,type:1,rnd:Math.random()},success:function(a){b.remove();location.href=location.href}})}).parent().find("#btnNO").bind("click",function(){b.slideUp(function(){b.remove()})})})});function doSubmit(){document.forms[0].submit()}
function selectFriEmail(b){document.getElementById("emaillist").value="";document.getElementById("namelist").value="";for(var a=1;10>=a;a++)if(""!=document.getElementById("email"+a).value||""!=document.getElementById("name"+a).value){document.getElementById("error"+a).innerHTML="";if(""==document.getElementById("email"+a).value)return document.getElementById("error"+a).innerHTML="\u8bf7\u8f93\u5165Email\u5730\u5740",document.getElementById("email"+a).focus(),!1;if(!isValidEmail(document.getElementById("email"+
a).value))return document.getElementById("error"+a).innerHTML="\u8bf7\u6b63\u786e\u8f93\u5165Email\u5730\u5740",document.getElementById("email"+a).focus(),!1;if(-1!=document.getElementById("emaillist").value.toLowerCase().indexOf(document.getElementById("email"+a).value.toLowerCase()))return document.getElementById("error"+a).innerHTML="\u8bf7\u4e0d\u8981\u91cd\u590d\u8f93\u5165Email\u5730\u5740",!1;if(""==document.getElementById("name"+a).value)return document.getElementById("error"+a).innerHTML=
"\u79f0\u547c\u53ef\u4ee5\u5e2e\u52a9\u670b\u53cb\u8ba4\u51fa\u4f60\uff0c\u4e5f\u597d\u8bb0\u3002",document.getElementById("name"+a).focus(),!1;document.getElementById("emaillist").value+=document.getElementById("email"+a).value+",";document.getElementById("namelist").value+=document.getElementById("name"+a).value+","}document.getElementById("emaillist").value=document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1);document.getElementById("namelist").value=
document.getElementById("namelist").value.substring(0,document.getElementById("namelist").value.length-1);document.forms[0].action="/members/friends/invite_select.aspx?profileurlno="+b;setTimeout(doSubmit,0)}
function goToPersonalityEmail(b,a){document.getElementById("emaillist").value="";document.getElementById("namelist").value="";for(var c=!1,d=0;d<a;d++)document.getElementById("emailselected"+d)&&!0==document.getElementById("emailselected"+d).checked&&(c=!0,""!=document.getElementById("email"+d).value&&""!=document.getElementById("name"+d).value&&(document.getElementById("emaillist").value+=document.getElementById("email"+d).value+",",document.getElementById("namelist").value+=document.getElementById("name"+
d).value+","));c?(document.getElementById("emaillist").value=document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1),document.getElementById("namelist").value=document.getElementById("namelist").value.substring(0,document.getElementById("namelist").value.length-1),document.forms[0].action="/members/friends/invite_personalize.aspx?profileurlno="+b,document.forms[0].submit()):(alert("\u8bf7\u9009\u62e9\u4f60\u8981\u9080\u8bf7\u7684\u670b\u53cb"),document.getElementById("emailselected0").focus())}
function inviteList(b,a){document.getElementById("writererror").innerHTML="";document.getElementById("emaildetailerror").innerHTML="";var c;""==document.getElementById("writer").value&&(document.getElementById("writererror").innerHTML="\u8bf7\u8f93\u5165\u4f60\u7684\u59d3\u540d",document.getElementById("writer").focus(),c=1);0==document.getElementById("emaildetail").value.length?(document.getElementById("emaildetailerror").innerHTML="\u8bf7\u8f93\u5165\u9080\u8bf7\u9644\u8a00",document.getElementById("emaildetail").focus(),
c=1):50<document.getElementById("emaildetail").value.length&&(document.getElementById("emaildetailerror").innerHTML="\u6700\u591a50\u5b57",document.getElementById("emaildetail").focus(),c=1);if(1==c)return!1;for(var d=c="",l="",n="",m=0;m<a;m++)document.getElementById("email"+m)&&""!=document.getElementById("email"+m).value&&document.getElementById("name"+m)&&""!=document.getElementById("name"+m)?(c+=escape(document.getElementById("email"+m).value),c+=",",d+=escape(document.getElementById("name"+
m).value),d+=","):document.getElementById("profileurlno"+m)&&(""!=document.getElementById("profileurlno"+m).value&&document.getElementById("name"+m)&&""!=document.getElementById("name"+m))&&(l+=escape(document.getElementById("profileurlno"+m).value),l+=",",n+=escape(document.getElementById("name"+m).value),n+=",");c={writer:escape(document.getElementById("writer").value),emaildetail:escape(document.getElementById("emaildetail").value),emaillist:""!=c?c.substring(0,c.length-1):"",namelist:""!=d?d.substring(0,
d.length-1):"",profileurlnolist:""!=l?l.substring(0,l.length-1):"",namelist1:""!=n?n.substring(0,n.length-1):""};jQuery.ajax({type:"GET",url:"/members/Ajax/FriendsInvite.ashx",dateType:"plain",data:c,success:function(a){eval(a);document.getElementById("successCount").value=successCount;document.getElementById("failedList").value=failedList;document.getElementById("notMainUid").value=notMainUid;document.forms[0].action="/members/friends/invite_success.aspx?profileurlno="+b;document.forms[0].submit()}})}
function checkSelectNum(b){checkNum=b.checked?checkNum+1:checkNum-1;10<checkNum&&(alert("\u6bcf\u6b21\u6700\u591a\u9080\u8bf7\u5341\u540d\u670b\u53cb"),b.checked=!1,checkNum-=1)}
function inviteListAgain(b,a){CheckUserProfileStatus();if("0"==isFUserRegister){var c=0;document.getElementById("emaillist").value="";document.getElementById("namelist").value="";document.getElementById("profileurlnolist").value="";document.getElementById("namelist1").value="";for(var d=1;d<=b;d++)null!=document.getElementById("list"+d)&&(document.getElementById("list"+d).checked&&!document.getElementById("list"+d).disabled)&&(document.getElementById("email"+d)&&""!=document.getElementById("email"+
d).value?(document.getElementById("emaillist").value+=document.getElementById("email"+d).value+",",document.getElementById("namelist").value+=document.getElementById("name"+d).value+",",c++):document.getElementById("prorileUrlNo"+d)&&""!=document.getElementById("prorileUrlNo"+d).value&&(document.getElementById("profileurlnolist").value+=document.getElementById("prorileUrlNo"+d).value+",",document.getElementById("namelist1").value+=document.getElementById("name"+d).value+",",c++));0<c?(document.getElementById("emaillist").value=
document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1),document.getElementById("namelist").value=document.getElementById("namelist").value.substring(0,document.getElementById("namelist").value.length-1),document.getElementById("profileurlnolist").value=document.getElementById("profileurlnolist").value.substring(0,document.getElementById("profileurlnolist").value.length-1),document.getElementById("namelist1").value=document.getElementById("namelist1").value.substring(0,
document.getElementById("namelist1").value.length-1),document.forms[0].action="/members/friends/invite_personalize.aspx?profileurlno="+a,document.forms[0].submit()):(alert("\u8bf7\u52fe\u9009\u8981\u91cd\u65b0\u53d1\u9001\u7684\u9080\u8bf7"),document.getElementById("list1").focus())}}
function inviteOldList(b,a){var c=0;document.getElementById("emaillist").value="";document.getElementById("namelist").value="";document.getElementById("oldfriendsidlist").value="";for(var d=1;d<=a;d++)null!=document.getElementById("oldlist"+d)&&document.getElementById("oldlist"+d).checked&&(document.getElementById("emaillist").value+=document.getElementById("oldEmail"+d).value+",",document.getElementById("namelist").value+=document.getElementById("oldName"+d).value+",",document.getElementById("oldfriendsidlist").value+=
document.getElementById("oldlist"+d).value,c++);0<c?(document.getElementById("emaillist").value=document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1),document.getElementById("namelist").value=document.getElementById("namelist").value.substring(0,document.getElementById("namelist").value.length-1),document.getElementById("oldfriendsidlist").value=document.getElementById("oldfriendsidlist").value.substring(0,document.getElementById("oldfriendsidlist").value.length-
1),document.forms[0].action="/members/friends/invite_personalize.aspx?profileurlno="+b,document.forms[0].submit()):(alert("\u8bf7\u52fe\u9009\u8981\u91cd\u65b0\u53d1\u9001\u7684\u9080\u8bf7"),document.getElementById("oldlist1").focus())}
function favoriteFriendDel(b,a){CheckUserProfileStatus();"0"==isFUserRegister&&jQuery.ajax({type:"GET",url:"/members/Ajax/FavoriteFriendStateChange.ashx",dateType:"plain",data:{id:a,deleted:"T"},success:function(a){document.getElementById("selectList"+b).parentNode.removeChild(document.getElementById("selectList"+b));OldFriendCount-=1;0==OldFriendCount&&document.getElementById("inviteoldfriends").parentNode.removeChild(document.getElementById("inviteoldfriends"))}})}
function favoriteFriendWait(b,a){jQuery.ajax({type:"GET",url:"/members/Ajax/FavoriteFriendStateChange.ashx",dateType:"plain",data:{id:a,deleted:"W"},success:function(a){document.getElementById("selectList"+b).parentNode.removeChild(document.getElementById("selectList"+b));OldFriendCount-=1;0==OldFriendCount&&(document.getElementById("focus_member_infor").parentNode.removeChild(document.getElementById("focus_member_infor")),document.getElementById("invitefriend").parentNode.removeChild(document.getElementById("invitefriend")))}})}
function indexGoToPersonalityEmail(b,a){document.getElementById("emaillist").value="";document.getElementById("namelist").value="";for(var c=1;c<=a;c++)null!=document.getElementById("email"+c)&&null!=document.getElementById("name"+c)&&(document.getElementById("emaillist").value+=document.getElementById("email"+c).value+",",document.getElementById("namelist").value+=document.getElementById("name"+c).value+",",document.getElementById("oldfriendsidlist").value+=document.getElementById("oldlist"+c).value);
document.getElementById("emaillist").value=document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1);document.getElementById("namelist").value=document.getElementById("namelist").value.substring(0,document.getElementById("namelist").value.length-1);document.getElementById("oldfriendsidlist").value=document.getElementById("oldfriendsidlist").value.substring(0,document.getElementById("oldfriendsidlist").value.length-1);document.forms[0].action="/members/friends/invite_personalize.aspx?profileurlno="+
b;document.forms[0].submit()}function refuse(b,a){CheckUserProfileStatus();"0"==isFUserRegister&&jQuery.ajax({type:"GET",url:"/members/Ajax/RefuseFriendsInvite.ashx",dateType:"plain",data:{id:a},success:function(a){listCount-=1;0==listCount?window.location.href=location.href:document.getElementById("list"+b).parentNode.removeChild(document.getElementById("list"+b))}})}
function acceptInvite(b,a){CheckUserProfileStatus();if("0"==isFUserRegister){for(var c=0,d={idCount:a},l=1;l<=a;l++)document.getElementById("listcheckbox"+l).checked?(d["id"+l]=document.getElementById("listcheckbox"+l).value,c++):d["id"+l]="";0==a?(alert("\u4f60\u6ca1\u6709\u6536\u5230\u4efb\u4f55\u9080\u8bf7"),document.getElementById("listcheckbox1").focus()):0==c?(alert("\u8bf7\u52fe\u9009\u8981\u63a5\u53d7\u7684\u9080\u8bf7"),document.getElementById("listcheckbox1").focus()):jQuery.ajax({type:"GET",
url:"/members/Ajax/AcceptInvite.ashx",dateType:"plain",data:d,success:function(a){eval(a);""!=returnValue&&alert(returnValue);window.location.href="/members/friends/attentiontome.aspx?profileurlno="+b}})}}
function InviteOne(b,a,c){jQuery("#emaildetailerror").html("").css({background:"none"});""==document.getElementById("emaildetailerror").innerHTML&&(jQuery("#emaildetailerror").html("\u6b63\u5728\u53d1\u9001...").css({color:"#666",background:"url(/members/img/loading.gif) no-repeat",paddingLeft:"18px"}),b={writer:escape(b),emaildetail:escape(document.getElementById("emaildetail").value),prorileurl:a,nickname:escape(c)},jQuery.ajax({type:"GET",url:"/members/Ajax/FriendInvite.ashx",dateType:"plain",
data:b,success:function(a){eval(a);"-100"==retcode?window.location.href="/members/CheckEmail.aspx?PreUrl="+window.location.href:(0==retcode?(jQuery("#returnValue").html("\u9080\u8bf7\u5df2\u7ecf\u53d1\u9001\uff01"),jQuery("#send_invitation_btn").html("\u9080\u8bf7\u5df2\u53d1").addClass("btn-invited").attr("id","")):jQuery("#returnValue").html("\u9080\u8bf7\u8fc7\u7a0b\u4e2d\u51fa\u73b0\u5f02\u5e38,\u8bf7\u5237\u65b0\u9875\u9762\u540e\u91cd\u65b0\u9080\u8bf7\uff01"),jQuery(".send_uplayer_con").hide(300),
jQuery(".send_uplayer_confirm").show(300),setTimeout(function(){jQuery("#send_invitation_uplayer").slideUp(300)},5E3))}}))}
function CheckUserProfileStatus(){jQuery.ajax({url:"/members/Ajax/CheckUserProfile.ashx?type=friends",type:"GET",async:!1,dataType:"text",timeout:1E3,error:function(b){return!1},success:function(b){if("-1"==b)alert("\u7528\u6237\u767b\u5f55\u65f6\u95f4\u8fc7\u957f\uff0c\u8bf7\u91cd\u65b0\u5237\u65b0\u7f51\u9875"),isFUserRegister=b;else if("0"==b)isFUserRegister=b;else return isFUserRegister=b,window.location=b,!1}})}
function showSpan(b,a){b.style.display="none";document.getElementById(a).style.display="block"}
function getPosition(){if(null===this.parentNode||"none"==this.style.display)return!1;var b=null,a=[];if(this.getBoundingClientRect){var b=this.getBoundingClientRect(),a=Math.max(document.documentElement.scrollTop,document.body.scrollTop),c=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);return{x:b.left+c,y:b.top+a}}if(document.getBoxObjectFor)b=document.getBoxObjectFor(this),a=this.style.borderLeftWidth?parseInt(this.style.borderLeftWidth):0,c=this.style.borderTopWidth?parseInt(this.style.borderTopWidth):
0,a=[b.x-a,b.y-c];else{a=[this.offsetLeft,this.offsetTop];b=this.offsetParent;if(b!=this)for(;b;)a[0]+=b.offsetLeft,a[1]+=b.offsetTop,b=b.offsetParent;if(-1!=this.ua.indexOf("opera")||-1!=(this.ua.indexOf("safari")&&"absolute"==this.style.position))a[0]-=document.body.offsetLeft,a[1]-=document.body.offsetTop}for(b=this.parentNode?this.parentNode:null;b&&"BODY"!=b.tagName&&"HTML"!=b.tagName;)a[0]-=b.scrollLeft,a[1]-=b.scrollTop,b=b.parentNode?b.parentNode:null;return{x:a[0],y:a[1]}}
jQuery(function(){jQuery("input[name=emailType]:radio").click(function(){var b=jQuery(this).attr("emailname");jQuery(this).blur();document.getElementById("emailType").value=jQuery(this).attr("value");jQuery(this).parent().parent().addClass("current").siblings().removeClass("current");jQuery(".fri_email_detail").show();document.getElementById("loginNameError").innerHTML="";document.getElementById("pwdError").innerHTML="";jQuery("#fri_email_type").text(b)});jQuery("#my_fri_infor .my_fri_infor").live("mouseover",
function(){jQuery(this).children(".close_btn").show()}).live("mouseout",function(){"none"==jQuery(".clue_uplayer").css("display")&&jQuery(this).children(".close_btn").hide()})});
function RadioChecked(b){if(1==b||document.getElementById("email_msn").checked)document.getElementById("email_msn").checked="checked",document.getElementById("emailType").value="Hotmail",document.getElementById("email_gmail").parentNode.parentNode.className="",document.getElementById("email_yahoo").parentNode.parentNode.className="",document.getElementById("email_sina").parentNode.parentNode.className="",document.getElementById("email_msn").parentNode.parentNode.className="current";if(2==b||document.getElementById("email_gmail").checked)document.getElementById("email_gmail").checked=
"checked",document.getElementById("emailType").value="GMail",document.getElementById("email_msn").parentNode.parentNode.className="",document.getElementById("email_yahoo").parentNode.parentNode.className="",document.getElementById("email_sina").parentNode.parentNode.className="",document.getElementById("email_gmail").parentNode.parentNode.className="current",jQuery("#fri_email_type").text(jQuery("#email_gmail").attr("emailname"));if(3==b||document.getElementById("email_yahoo").checked)document.getElementById("email_yahoo").checked=
"checked",document.getElementById("emailType").value="Yahoo",document.getElementById("email_msn").parentNode.parentNode.className="",document.getElementById("email_gmail").parentNode.parentNode.className="",document.getElementById("email_sina").parentNode.parentNode.className="",document.getElementById("email_yahoo").parentNode.parentNode.className="current",jQuery("#fri_email_type").text(jQuery("#email_yahoo").attr("emailname"));if(4==b||document.getElementById("email_sina").checked)document.getElementById("email_sina").checked=
"checked",document.getElementById("emailType").value="Sina",document.getElementById("email_msn").parentNode.parentNode.className="",document.getElementById("email_yahoo").parentNode.parentNode.className="",document.getElementById("email_gmail").parentNode.parentNode.className="",document.getElementById("email_sina").parentNode.parentNode.className="current",jQuery("#fri_email_type").text(jQuery("#email_sina").attr("emailname"))}
function getContacts(b){var a=0;document.getElementById("loginNameError").innerHTML="";document.getElementById("pwdError").innerHTML="";""==document.getElementById("loginName").value?(document.getElementById("loginNameError").innerHTML="\u8bf7\u8f93\u5165\u7528\u6237\u540d",document.getElementById("loginName").focus(),a=1):"Hotmail"==document.getElementById("emailType").value?isValidEmail(document.getElementById("loginName").value)||(document.getElementById("loginNameError").innerHTML="\u8bf7\u6b63\u786e\u8f93\u5165Email\u5730\u5740",
document.getElementById("loginName").focus(),a=1):""==document.getElementById("pwd").value&&(document.getElementById("pwdError").innerHTML="\u8bf7\u8f93\u5165\u5bc6\u7801",document.getElementById("pwd").focus(),a=1);if(0==a){var c={emailType:escape(document.getElementById("emailType").value),mail:escape(document.getElementById("loginName").value),pwd:escape(document.getElementById("pwd").value)};jQuery(".send_inviBtn").hide();jQuery(".loading_pic").show();jQuery.ajax({url:"/members/Ajax/GetContactsByEmail.ashx",
type:"GET",dataType:"plain",data:c,error:function(a){document.getElementById("loginNameError").innerHTML="\u7a0b\u5e8f\u5f02\u5e38";jQuery(".loading_pic").hide();jQuery(".send_inviBtn").show()},success:function(c){eval(c);""!=a?(document.getElementById("loginNameError").innerHTML=a,jQuery(".loading_pic").hide(),jQuery(".send_inviBtn").show()):0<emaillist.length&&0<namelist.length?(document.getElementById("emaillist").value=emaillist,document.getElementById("namelist").value=namelist,document.forms[0].action=
"/members/friends/invite_select.aspx?profileurlno="+b,document.forms[0].submit()):(document.getElementById("loginNameError").innerHTML="\u8be5\u90ae\u7bb1\u6ca1\u6709\u597d\u53cb",jQuery(".loading_pic").hide(),jQuery(".send_inviBtn").show())}})}}var CancelFriendAjaxurl="/members/Ajax/CancelFriend.ashx";
function CancelFriend(b,a,c){b=b?b:event;var d=b.srcElement||b.target,l=jQuery(".clue_uplayer");l.css({display:"none",left:jQuery(d).offset().left-27+"px",top:jQuery(d).offset().top+5+"px"}).slideDown(250).find("#btnYes").unbind("click").bind("click",function(){jQuery.ajax({type:"GET",url:CancelFriendAjaxurl,dateType:"plain",data:{profileurlno:a,type:c},success:function(a){jQuery(d).parent().css("background","#EAF3FC");jQuery(d).parent().animate({width:0},function(){jQuery(d).parent().remove()});
l.slideUp(250)}})}).end().find("#btnNO").bind("click",function(){l.slideUp(250);jQuery(".close_btn").hide()})}function CheckAll(b,a){for(var c=jQuery("input[name=checkAll]").attr("checked"),d=1;d<=b;d++)null==document.getElementById(a+d)||document.getElementById(a+d).disabled||(document.getElementById(a+d).checked=c)}
function CheckAllToInvite(b){for(var a=jQuery("input[name=checkAll]").attr("checked"),c=0;c<b;c++)null==document.getElementById("emailselected"+c)||document.getElementById("emailselected"+c).disabled||(document.getElementById("emailselected"+c).checked=a)}
function inviteHotelGetContacts(b){var a=0;document.getElementById("loginError").innerHTML="";document.getElementById("loginError").style.display="none";document.getElementById("searchTitle").style.display="block";document.getElementById("loginNameError").innerHTML="";document.getElementById("pwdError").innerHTML="";""==document.getElementById("loginName").value?(document.getElementById("loginNameError").innerHTML="\u8bf7\u8f93\u5165\u7528\u6237\u540d",document.getElementById("loginName").focus(),
a=1):"Hotmail"==document.getElementById("emailType").value?isValidEmail(document.getElementById("loginName").value)||(document.getElementById("loginNameError").innerHTML="\u8bf7\u6b63\u786e\u8f93\u5165Email\u5730\u5740",document.getElementById("loginName").focus(),a=1):""==document.getElementById("pwd").value&&(document.getElementById("pwdError").innerHTML="\u8bf7\u8f93\u5165\u5bc6\u7801",document.getElementById("pwd").focus(),a=1);0==a&&(b={emailType:escape(document.getElementById("emailType").value),
mail:escape(document.getElementById("loginName").value),pwd:escape(document.getElementById("pwd").value)},jQuery(".send_inviBtn").hide(),jQuery(".loading_pic").show(),jQuery.ajax({url:"/members/Ajax/GetContactsByEmailInLvping.ashx",type:"GET",dataType:"plain",data:b,error:function(a){document.getElementById("searchTitle").style.display="none";document.getElementById("loginError").style.display="block";document.getElementById("loginError").innerHTML="\u7a0b\u5e8f\u5f02\u5e38";jQuery(".loading_pic").hide();
jQuery(".send_inviBtn").show()},success:function(b){eval(b);""!=a?(document.getElementById("searchTitle").style.display="none",document.getElementById("loginError").style.display="block",document.getElementById("loginError").innerHTML=a,jQuery(".loading_pic").hide(),jQuery(".send_inviBtn").show()):0<emaillist.length&&0<namelist.length?(document.getElementById("emaillist").value=emaillist,document.getElementById("namelist").value=namelist,document.forms[0].action="/members/writereview/inviteselect.aspx",
document.forms[0].submit()):(document.getElementById("searchTitle").style.display="none",document.getElementById("loginError").style.display="block",document.getElementById("loginError").innerHTML="\u67e5\u627e\u5b8c\u6bd5\uff0c\u6ca1\u6709\u627e\u5230\u53ef\u4ee5\u9080\u8bf7\u4f60\u7684\u670b\u53cb\uff0c\u8bd5\u8bd5\u6362\u4e2a\u90ae\u7bb1",jQuery(".loading_pic").hide(),jQuery(".send_inviBtn").show())}}))}
function goToWriteEmail(b){document.getElementById("emaillist").value="";document.getElementById("namelist").value="";for(var a=!1,c=0;c<b;c++)document.getElementById("emailselected"+c)&&!0==document.getElementById("emailselected"+c).checked&&(a=!0,""!=document.getElementById("email"+c).value&&""!=document.getElementById("name"+c).value&&(document.getElementById("emaillist").value+=document.getElementById("email"+c).value+",",document.getElementById("namelist").value+=document.getElementById("name"+
c).value+","));a?(document.getElementById("emaillist").value=document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1),document.getElementById("namelist").value=document.getElementById("namelist").value.substring(0,document.getElementById("namelist").value.length-1),document.forms[0].action="/members/writereview/WriteEmail.aspx",document.forms[0].submit()):(alert("\u8bf7\u9009\u62e9\u4f60\u8981\u9080\u8bf7\u7684\u670b\u53cb"),document.getElementById("emailselected0").focus())}
function HotelReviewInviteSendEmail(b){document.getElementById("emaillist").value="";document.getElementById("sendemail").value="";for(var a=!1,c=0;c<b;c++)document.getElementById("emailselected"+c)&&!0==document.getElementById("emailselected"+c).checked&&(a=!0,""!=document.getElementById("email"+c).value&&(document.getElementById("emaillist").value+=document.getElementById("email"+c).value+","));if(a){if(""==document.getElementById("topic").value)return alert("\u8bf7\u586b\u5199\u90ae\u4ef6\u4e3b\u9898"),
document.getElementById("topic").focus(),!1;if(""==document.getElementById("mainbody").value)return alert("\u8bf7\u586b\u5199\u6b63\u6587"),document.getElementById("mainbody").focus(),!1;document.getElementById("sendemail").value=1;document.getElementById("emaillist").value=document.getElementById("emaillist").value.substring(0,document.getElementById("emaillist").value.length-1);return!0}alert("\u8bf7\u9009\u62e9\u4f60\u8981\u9080\u8bf7\u7684\u670b\u53cb");document.getElementById("emailselected0").focus();
return!1}function showEmailSendrTips(b){if("1"==document.getElementById("postBack").value){var a=jQuery(window).width(),c=jQuery(window).height(),d=jQuery(".trip_email_send_result"),l=d.width()+40,n=d.height()+40;""!=b&&d.find(".trip_email_result").html('<p class="send_error">'+b+"</p>");d.css({left:a/2-l/2+"px",top:c/2-n/2+"px"}).show();jQuery(".trip_email_send_result a.trip_cancel_btn").bind("click",function(){d.hide()});document.getElementById("postBack").value="2"}}
jQuery("#send_invitation_btn").bind("click",function(b){b=$(this);if("\u8bf7\u7a0d\u7b49..."==b.html())return!1;b.html("\u8bf7\u7a0d\u7b49...");b=$(this).attr("profileurlno");var a=$(this).attr("sessionprofileurlno");jQuery.ajax({type:"GET",url:"/members/ajax/addfriend.ashx",dateType:"plain",data:{profileurlno:b,sessionprofileurlno:a,rnd:Math.random()},success:function(a){location.href=location.href}})});
$(function(){$.ajax({url:"/membersite/Ajax/GetCityMasterHtml.ashx?id="+$("#hdn_userid").val(),type:"post",success:function(b){b&&($(".info-badge").append('<a class="badge_cs" href="javascript:;"></a>'),$(".info-badge").after(b),huizhan_v1_callback())}});$.browser.msie&&9>$.browser.version&&$(".badge_box").addClass("hack_ie8");huizhan_v1_callback()});
function huizhan_v1_callback(){$(".info-badge a").on("mouseenter",function(){var b=$(this).attr("class"),a=$(this).offset(),c=$(".badge_box."+b).outerWidth(),d=$(".badge_box."+b).outerHeight(),l=$(this).parent(".info-badge").offset(),n=$(this).parents(".item").offset();$(".badge_box."+b).css({top:a.top-l.top-d+3,left:a.left-n.left-c/2+16}).show()}).on("mouseleave",function(){var b=$(this).attr("class");$(".badge_box."+b).hide()});$(".badge_box").on("mouseenter",function(){$(this).show()}).on("mouseleave",
function(){$(this).hide()})};
