/* 2018-09-12 10:18:13 j.zhou */
var cQuery={};
$(function(){var b=$("<div></div>");$(document.body).append(b);var e=function(b,a){var c=this,d=$(b);this.$element=d;this.oldValue="";this.alignRight=a.alignRight||!1;this.title=a.title||"\u652f\u6301\u4e2d\u6587/\u62fc\u97f3/\u7b80\u62fc\u8f93";this.drawHtml=a.drawHtml;this.eventControl=a.eventControl||function(){};this.addBox();d.keyup(function(){$(this).val()!=c.oldValue&&c.blur()});d.click(function(a){c.focus();c.$element.select();a.stopPropagation()});$(document).click(function(){c.blur()});$(window).resize(function(){c.blur()})};
e.prototype={container:"",tabContainer:"",hasHtml:!1,selectHtml:'<div class="city_select_popup"><a class="close" href="javascript:;">\u00d7</a><p class="title"></p><ul class="tab_box"></ul></div>',addBox:function(){this.container=$(this.selectHtml);this.tabContainer=this.container.find(".tab_box");b.append(this.container);this.container.find(".title").text(this.title)},focus:function(){this.$element.focus();$(".city_select_popup").hide();$(".city_suggest_popup").hide();this.oldValue=this.$element.val();
this.hasHtml?(this.setOffset(),this.container.show()):this.displayPopup()},blur:function(){this.container.hide()},setOffset:function(){var b=this.$element.offset(),a=this.$element.outerHeight()-1,c=b.left;this.alignRight&&(c=c+this.$element.outerWidth()-this.container.outerWidth());this.container.css({top:b.top+a,left:c})},displayPopup:function(){var b=this;this.drawHtml(function(a){b.container.find(".city_item").remove();b.tabContainer.empty();b.container.append(a.html);b.tabContainer.append(a.tabHtml);
b.setOffset();b.addEventListener();b.eventControl(b);b.container.show();b.hasHtml=!0},b)},addEventListener:function(){var b=this,a=this.tabContainer,c=this.container.find(".city_item");this.container.click(function(a){a.stopPropagation()});this.container.find(".close").click(function(a){b.blur();a.stopPropagation()});a.find("li").on("click",function(b){var k=$(this).index();a.find("li").removeClass("current");$(this).addClass("current");c.removeClass("current");c.eq(k).addClass("current");b.stopPropagation()})}};
$.fn.citySelect=function(b){return this.each(function(){new e(this,b)})}});cQuery={};
$(function(){var b=$("<div></div>");$(document.body).append(b);var e=function(b,a){var c=this,d=$(b);this.$element=d;this.container="";this.firstData=null;this.placeholder=a.placeholder||"";this.formatData=a.formatData;this.eventControl=a.eventControl||function(){};this.cannotToCache=a.cannotToCache||!1;this.gos=0;this.oldValue=d.val();this.pageNum=0;this.totlePage=1;this.cache={};this.addBox();this.timer=null;d.keyup(function(a){c.onKeyup(a)});d.click(function(a){c.oldValue=c.$element.val();a.stopPropagation()});
$(document).click(function(){c.hidePopup()});$(window).resize(function(){c.hidePopup()})};e.prototype={kCode:{ENTER:13,UP:38,DOWN:40,ESC:27},perPageNum:10,suggestHtml:'<div class="city_suggest_popup"></div>',addBox:function(){var k=this;this.container=$(this.suggestHtml);b.append(this.container);this.container.click(function(a){k.$element.focus();a.stopPropagation()})},addToCache:function(b,a){!this.cannotToCache&&0<a.length&&(this.cache[b]=[],this.cache[b]=a)},checkCache:function(b){return this.cache[b]?
!0:!1},setOffset:function(){var b=this.$element.offset(),a=this.$element.outerHeight()-1;this.container.css({top:b.top+a,left:b.left})},checkValue:function(){""!=this.$element.val()&&this.$element.val()!=this.placeholder||this.hidePopup();if(this.$element.val()!=this.oldValue){var b=this,a=function(){b.showPopup();clearTimeout(b.timer);b.timer=null};b.timer||(b.timer=setTimeout(a,200))}this.oldValue=this.$element.val()},onKeyup:function(b){switch(b.keyCode){case this.kCode.UP:b=this.container.find(".city_suggest_item");
1<b.length?(this.gos--,-1==this.gos&&(this.gos=b.length-1),this.selected(b.eq(this.gos))):1==b.length&&this.selected(b.eq(0));break;case this.kCode.DOWN:b=this.container.find(".city_suggest_item");1<b.length?(this.gos++,1!=this.gos||b.hasClass("current")||(this.gos=0),this.gos==b.length&&(this.gos=0),this.selected(b.eq(this.gos))):1==b.length&&this.selected(b.eq(0));break;case this.kCode.ENTER:this.container.find(".city_suggest_item").eq(this.gos).trigger("click");break;case this.kCode.ESC:this.$element.val("");
this.hidePopup();break;default:this.checkValue()}},selected:function(b){this.container.find(".city_suggest_item").removeClass("current");b.addClass("current")},hidePopup:function(){clearTimeout(this.timer);this.timer=null;this.container.hide()},showPopup:function(b){var a=this;(b=this.$element.val())&&(this.checkCache(b)?this.displayPopup(this.cache[b]):a.formatData(b,function(c){a.addToCache(b,c);a.displayPopup(c)}))},displayPopup:function(b){this.pageNum=0;this.drawHtml(b);this.drawPageHtml();this.setOffset();
this.eventControl(this);this.container.show();this.pageControl(b)},drawHtml:function(b){this.container.find("div").not(".city_suggest_pager").remove();this.gos=0;var a="",c=b.length,d=Math.ceil(c/this.perPageNum),g=this.pageNum*this.perPageNum,e=(this.pageNum+1)*this.perPageNum,e=e>c?c:e;this.totlePage=d;if(0<c)for(this.firstData=b[0];g<e;g++)if(c=b[g],c.showRight)a+='<div class="city_suggest_item" data="'+c.data+'"><span class="fl">'+c.text+'</span><span class="fr">'+c.right+"</span></div>";else{if(a=
c.noAirPort?a+('<div class="city_suggest_noAir" data="'+c.data+'">'+c.text+'<span class="orange">&nbsp;-\u8be5\u57ce\u5e02\u6ca1\u6709\u673a\u573a</span></div>'):a+('<div class="city_suggest_item" data="'+c.data+'">'+c.text+"</div>"),c.airPort&&0<c.airPort.length)for(var d=0,m=c.airPort.length;d<m;d++)a+='<div class="city_suggest_item gray" data="'+c.data+'" data-airPort="'+c.airPort[d]+'">'+c.airPortText[d]+"</div>"}else this.firstData="",a+='<div class="city_suggest_null">\u5bf9\u4e0d\u8d77\uff0c\u6ca1\u6709\u627e\u5230\u5339\u914d\u7684\u5173\u952e\u5b57</div>';
this.container.prepend(a)},drawPageHtml:function(){this.container.find(".city_suggest_pager").remove();var b="",a=this.totlePage,c=0;if(1<a){for(;c<a;c++)b=0===c?b+'<a class="page_num active" href="javascript:;">1</a>':3>c?b+('<a class="page_num" href="javascript:;">'+(c+1)+"</a>"):b+('<a class="page_num" href="javascript:;" style="display: none;">'+(c+1)+"</a>");b='<div class="city_suggest_pager">'+('<a class="gray page_prev" href="javascript:;">&lt;</a>'+b+'<a class="page_next" href="javascript:;">&gt;</a>')+
"</div>"}this.container.append(b)},pageControl:function(b){var a=this,c=this.container.find(".city_suggest_pager");c.find("a").click(function(d){d=$(this);var g=c.find(".page_prev"),e=c.find(".page_next"),m=c.find(".page_num"),h=a.pageNum,v=a.totlePage;if(!d.hasClass("gray")&&!d.hasClass("active")){d.hasClass("page_prev")?(h-=1,e.removeClass("gray")):d.hasClass("page_next")?(h+=1,g.removeClass("gray")):h=parseInt(d.text(),10)-1;var f=h-1,p=h+1;0>=f&&(p=2);p>=v&&(f=v-3);m.each(function(a){a>=f&&a<=
p?$(this).show():$(this).hide()});0===h?(g.addClass("gray"),e.removeClass("gray")):h===v-1?(e.addClass("gray"),g.removeClass("gray")):(g.removeClass("gray"),e.removeClass("gray"));c.find("a.page_num").removeClass("active").eq(h).addClass("active");a.pageNum=h;a.drawHtml(b);a.eventControl(a)}})}};$.fn.citySuggest=function(b){return this.each(function(){new e(this,b)})}});var CitySuggestFilter=function(b){this._init(b)};
CitySuggestFilter.prototype={sort:"^0$ ^1$ ^3+$ ^0 ^1 ^3+ 0 1 3+".split(" "),_colsHash:null,_displayHash:{left:0,right:1,text:1},message:{sort:[]},_init:function(b){b=b||{};var e=$.type(b.sort);if(b.sort&&"array"==e||"function"==e)this.sort=b.sort,this._sortReString=null;this.sortFunction=b.sortFunction||this.sortFunction;b.message&&(this.message=$.extend(!0,{},this.message,b.message));this._colsHash=b._colsHash||this._colsHash;b._displayHash&&(this._displayHash=$.extend(!0,{},this._displayHash,b._displayHash))},
sortFunction:function(b,e){return b.left>e.left?1:b.left==e.left?0:-1},_initSort:function(){if(!this._sortReString){var b=this._sortReString={accurate:[],vague:[]},e=0,k=0;switch($.type(this.sort)){case "array":for(var a=0,c=this.sort.length;a<c;a++){var d=this.sort[a].match(/^(\^?)([^\^\$\|@\r\n\+]+)(\+?)(\$?)$/);if(d){if(/^\d$/.test(d[2]))d[2]=parseInt(d[2],10);else if(d[2]in this._colsHash)d[2]=this._colsHash[d[2]];else continue;var g=+d[2]||d[3]?"([^\\|@]*\\|){"+d[2]+(d[3]?",":"")+"}":"";b.accurate[e++]=
["@("+g,"","(\\|[^@]*)?)(?=@)"];b.vague[k++]=["@("+g+(d[1]?"":"[^\\|@]*"),"",(d[4]?"(\\|[^@]*)?":"[^@]*")+")(?=@)"]}}}}},getfilterData:function(b,e,k,a){this._initSort();var c=this,d=[],g=0,w=b;switch($.type(this.sort)){case "array":b=this._sortReString[k?"accurate":"vague"];k="array"==$.type(this.message.sort)?this.message.sort:[];for(var m=0,h=b.length;m<h;m++){b[m][1]=e;var v=RegExp(b[m].join(""),"gi"),f=[],p=0,w=w.replace(v,function(a,b){var d=b.split("|"),d={left:d[c._displayHash.left]||"",right:d[c._displayHash.right]||
"",text:d[c._displayHash.text]||"",data:b};f[p++]=d;return""});if(p){f.sort(this.sortFunction);if(a)return f[0].data;k[m]&&f.unshift($.tmpl.render(k[m],{val:e,items:f}));d[g++]=f}}if(a)return!1;break;case "function":f=this.sort(b,e,k,a);if(a)return f.length?f[0].data:!1;d[g++]=f;break;default:return!1}return d=Array.prototype.concat.apply([],d)}};
(function(b){b.pageEventBind=function(){function e(a,c,d){""==a||"0"==a||a>c||/\D/g.test(a)?(d.val(""),k(d)):b.pageLinkJump&&b.pageLinkJump(a,d)}function k(a){var b=a.clone(),d=a.offset(),g=0;a.css("visibility","hidden");b.css({position:"absolute",top:d.top+"px",left:d.left+"px",width:"18px",height:"16px",border:"1px solid #ccc"}).appendTo("body");var e=setInterval(function(){g++;b.css({top:d.top+2*Math.sin(g)+"px",left:d.left+1*Math.cos(g)+"px"});15==g&&(clearInterval(e),a.css("visibility","visible"),
b.remove())},30)}b(".pager_v1").each(function(){var a=parseInt(b(this).find(".numpage").text()),c=b(this).find("span input");c.on("keyup",function(d){var g=b(this).val();/\D/g.test(g)&&b(this).val("");13==d.keyCode&&e(g,a,c)}).parent("span").siblings(".gopage").on("click",function(){var b=c.val();e(b,a,c)})})};b.pageEventBind()})(jQuery);
(function(b){b.fn.scriptNodeAsync=function(e){e=b.extend({color:"#fff",top:0},e);return this.each(function(){var e=b(this);b(this).parent();var a=b.trim(b(this).val()),a=a.replace("<script",""),a=b.trim(a.replace(">\x3c/script>","")),c=a.split(" "),d=0,g=/(.*?)="(.*?)"/i,a=document.createElement("script");a.async=!0;for(d in c){var w=c[d].match(g);a.setAttribute(w[1],w[2])}c=e[0];c.parentNode.insertBefore(a,c);e.remove()})};b(function(){var e=GS.throttle(function(){var e=document.documentElement.clientHeight,
a=b(window).scrollTop();b("textarea.gs_async").each(function(c){c=b(this).parent().offset().top;a+e>c&&b(this).scriptNodeAsync()})},1E3);b(window).scroll(e)})})(jQuery);
(function(b){function e(a,c,d,l){l={data:l||(c?c.data:{}),_wrap:c?c._wrap:null,tmpl:null,parent:c||null,nodes:[],calls:m,nest:h,wrap:v,html:f,update:p};a&&b.extend(l,a,{nodes:[],parent:c});d&&(l.tmpl=d,l._ctnt=l._ctnt||l.tmpl(b,l),l.key=++B,(C.length?A:u)[B]=l);return l}function k(c,d,e){var l;e=e?b.map(e,function(a){return"string"===typeof a?c.key?a.replace(/(<\w+)(?=[\s>])(?![^>]*_tmplitem)([^>]*)/g,"$1 "+n+'="'+c.key+'" $2'):a:k(a,c,a._ctnt)}):c;if(d)return e;e=e.join("");e.replace(/^\s*([^<\s][^<]*)?(<[\w\W]+>)([^>]*[^>\s])?\s*$/,
function(c,d,x,e){l=b(x).get();w(l);d&&(l=a(d).concat(l));e&&(l=l.concat(a(e)))});return l?l:a(e)}function a(a){var c=document.createElement("div");c.innerHTML=a;return b.makeArray(c.childNodes)}function c(a){return new Function("jQuery","$item","var $=jQuery,call,_=[],$data=$item.data;with($data){_.push('"+b.trim(a).replace(/([\\'])/g,"\\$1").replace(/[\r\t\n]/g," ").replace(/\$\{([^\}]*)\}/g,"{{= $1}}").replace(/\{\{(\/?)(\w+|.)(?:\(((?:[^\}]|\}(?!\}))*?)?\))?(?:\s+(.*?)?)?(\(((?:[^\}]|\}(?!\}))*?)\))?\s*\}\}/g,
function(a,c,d,x,e,f,h){a=b.tmpl.tag[d];if(!a)throw"Template command not found: "+d;d=a._default||[];f&&!/\w$/.test(e)&&(e+=f,f="");e?(e=g(e),h=h?","+g(h)+")":f?")":"",h=f?-1<e.indexOf(".")?e+f:"("+e+").call($item"+h:e,f=f?h:"(typeof("+e+")==='function'?("+e+").call($item):("+e+"))"):f=h=d.$1||"null";x=g(x);return"');"+a[c?"close":"open"].split("$notnull_1").join(e?"typeof("+e+")!=='undefined' && ("+e+")!=null":"true").split("$1a").join(f).split("$1").join(h).split("$2").join(x?x.replace(/\s*([^\(]+)\s*(\((.*?)\))?/g,
function(a,b,c,d){return(d=d?","+d+")":c?")":"")?"("+b+").call($item"+d:a}):d.$2||"")+"_.push('"})+"');}return _;")}function d(a,c){a._wrap=k(a,!0,b.isArray(c)?c:[t.test(c)?c:b(c).html()]).join("")}function g(a){return a?a.replace(/\\'/g,"'").replace(/\\\\/g,"\\"):null}function w(a){function c(a){function x(a){a+=d;q=f[a]=f[a]||e(q,u[q.parent.key+d]||q.parent,null,!0)}var l,g=a,q,z;if(z=a.getAttribute(n)){for(;g.parentNode&&1===(g=g.parentNode).nodeType&&!(l=g.getAttribute(n)););l!==z&&(g=g.parentNode?
11===g.nodeType?0:g.getAttribute(n)||0:0,(q=u[z])||(q=A[z],q=e(q,u[g]||A[g],null,!0),q.key=++B,u[B]=q),y&&x(z));a.removeAttribute(n)}else y&&(q=b.data(a,"tmplItem"))&&(x(q.key),u[q.key]=q,g=(g=b.data(a.parentNode,"tmplItem"))?g.key:0);if(q){for(l=q;l&&l.key!=g;)l.nodes.push(a),l=l.parent;delete q._ctnt;delete q._wrap;b.data(a,"tmplItem",q)}}var d="_"+y,l,g,f={},h,k,m;h=0;for(k=a.length;h<k;h++)if(1===(l=a[h]).nodeType){g=l.getElementsByTagName("*");for(m=g.length-1;0<=m;m--)c(g[m]);c(l)}}function m(a,
b,c,d){if(!a)return C.pop();C.push({_:a,tmpl:b,item:this,data:c,options:d})}function h(a,c,d){return b.tmpl(b.template(a),c,d,this)}function v(a,c){var d=a.options||{};d.wrapped=c;return b.tmpl(b.template(a.tmpl),a.data,d,a.item)}function f(a,c){var d=this._wrap;return b.map(b(b.isArray(d)?d.join(""):d).filter(a||"*"),function(a){if(c)a=a.innerText||a.textContent;else{var b;(b=a.outerHTML)||(b=document.createElement("div"),b.appendChild(a.cloneNode(!0)),b=b.innerHTML);a=b}return a})}function p(){var a=
this.nodes;b.tmpl(null,null,null,this).insertBefore(a[0]);b(a).remove()}var r=b.fn.domManip,n="_tmplitem",t=/^[^<]*(<[\w\W]+>)[^>]*$|\{\{\! /,u={},A={},s,D={key:0,data:{}},B=0,y=0,C=[];b.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,c){b.fn[a]=function(d){var e=[];d=b(d);var g,f,h;g=1===this.length&&this[0].parentNode;s=u||{};if(g&&11===g.nodeType&&1===g.childNodes.length&&1===d.length)d[c](this[0]),e=this;else{f=0;for(h=
d.length;f<h;f++)y=f,g=(0<f?this.clone(!0):this).get(),b.fn[c].apply(b(d[f]),g),e=e.concat(g);y=0;e=this.pushStack(e,a,d.selector)}d=s;s=null;b.tmpl.complete(d);return e}});b.fn.extend({tmpl:function(a,c,d){return b.tmpl(this[0],a,c,d)},tmplItem:function(){return b.tmplItem(this[0])},template:function(a){return b.template(a,this[0])},domManip:function(a,c,d){if(a[0]&&a[0].nodeType){for(var e=b.makeArray(arguments),g=a.length,f=0,h;f<g&&!(h=b.data(a[f++],"tmplItem")););1<g&&(e[0]=[b.makeArray(a)]);
h&&y&&(e[2]=function(a){b.tmpl.afterManip(this,a,d)});r.apply(this,e)}else r.apply(this,arguments);y=0;!s&&b.tmpl.complete(u);return this}});b.extend({tmpl:function(a,c,g,f){var h=!f;if(h)f=D,a=b.template[a]||b.template(null,a),A={};else if(!a)return a=f.tmpl,u[f.key]=f,f.nodes=[],f.wrapped&&d(f,f.wrapped),b(k(f,null,f.tmpl(b,f)));if(!a)return[];"function"===typeof c&&(c=c.call(f||{}));g&&g.wrapped&&d(g,g.wrapped);c=b.isArray(c)?b.map(c,function(b){return b?e(g,f,a,b):null}):[e(g,f,a,c)];return h?
b(k(f,null,c)):c},tmplItem:function(a){var c;for(a instanceof b&&(a=a[0]);a&&1===a.nodeType&&!(c=b.data(a,"tmplItem"))&&(a=a.parentNode););return c||D},template:function(a,d){return d?("string"===typeof d?d=c(d):d instanceof b&&(d=d[0]||{}),d.nodeType&&(d=b.data(d,"tmpl")||b.data(d,"tmpl",c(d.innerHTML))),"string"===typeof a?b.template[a]=d:d):a?"string"!==typeof a?b.template(null,a):b.template[a]||b.template(null,t.test(a)?a:b(a)):null},encode:function(a){return(""+a).split("<").join("&lt;").split(">").join("&gt;").split('"').join("&#34;").split("'").join("&#39;")}});
b.extend(b.tmpl,{tag:{tmpl:{_default:{$2:"null"},open:"if($notnull_1){_=_.concat($item.nest($1,$2));}"},wrap:{_default:{$2:"null"},open:"$item.calls(_,$1,$2);_=[];",close:"call=$item.calls();_=call._.concat($item.wrap(call,_));"},each:{_default:{$2:"$index, $value"},open:"if($notnull_1){$.each($1a,function($2){with(this){",close:"}});}"},"if":{open:"if(($notnull_1) && $1a){",close:"}"},"else":{_default:{$1:"true"},open:"}else if(($notnull_1) && $1a){"},html:{open:"if($notnull_1){_.push($1a);}"},"=":{_default:{$1:"$data"},
open:"if($notnull_1){_.push($.encode($1a));}"},"!":{open:""}},complete:function(){u={}},afterManip:function(a,c,d){var e=11===c.nodeType?b.makeArray(c.childNodes):1===c.nodeType?[c]:[];d.call(a,c);w(e);y++}})})(jQuery);
$(function(){$("#ws_left .ws_switchtab").hover(function(){var a=$(this),b=a.index("#ws_left .ws_switchtab");a.data("index",b).addClass("switch_over");$(".ws_switchbox").eq(b).show()},function(){var a=$(this);a.removeClass("switch_over");a=a.data("index");a=$(".ws_switchbox").eq(a);"block"==a.css("display")&&a.hide()});$("#ws_left .ws_switchbox").hover(function(){var a=$(this).show().index("#ws_left .ws_switchbox");$("#ws_left .ws_switchtab").eq(a).addClass("switch_over")},function(){var a=$(this).hide().index("#ws_left .ws_switchbox");
$("#ws_left .ws_switchtab").eq(a).removeClass("switch_over")});$("#askCarousel .side_list .side_item:last-child").css("border","none");$("#topicCarousel").carousel();$("#commentCarousel").carousel();$("#askCarousel").carousel();$("#travelerTab li").on("click",function(){var a=$(this);a.hasClass("current")||(a.addClass("current").siblings().removeClass("current"),a=a.index(),$("#travelerWrap .traveler_list").eq(a).addClass("current").siblings().removeClass("current"))});$("#citySelect dt").on("click",
function(a){var b=$(this),d=b.siblings("dd");d.hasClass("current")?(d.removeClass("current"),b.removeClass("active")):(d.addClass("current"),b.addClass("active"));a.stopPropagation();return!1});$("#citySelect dd").on("click",function(a){a.stopPropagation();return!1});$("#citySelect dd.city_searchBox a").on("click",function(){var a=$(this),b=$.trim(a.text()),a=a.attr("data-href");$("#citySelect dt strong").text("\u6211\u5728"+b);$("#citySelect dt").removeClass("active");$("#citySelect dd").removeClass("current");
INTERFACE.changeCityFn({ename:a},function(a){var e=a.District,k=$(".switch_first"),m=e.CurCity.Url,h=e.Nearby,v=h.length,f=0,p="",r=e.City,n=e.Poi;GSDistrictId=e.CurCity.DistrictId;for(k.find("dt a").text(b+"\u5468\u8fb9\u65c5\u6e38").attr("href",m);f<v;f++)m=h[f],p+='<a href="'+m.Url+'" target="_blank">'+m.Name+"</a>";k.find("dd").html(p);k=$(".ws_switchbox").eq(0).find(".poi_list").eq(0);h=$(".ws_switchbox").eq(0).find(".poi_list").eq(1);v=[];p=[];for(f=0;f<r.length;f++)m=r[f],v.push('<span class="f_line">|<a href="'+
m.Url+'" target="_blank">'+m.Name+"</a></span>");for(f=0;f<n.length;f++)r=n[f],p.push('<span class="f_line">|<a href="'+r.Url+'" target="_blank">'+r.Name+"</a></span>");k.html(v.join(""));h.html(p.join(""));e=void 0!==e.CurCity.EName?e.CurCity.EName:"";n=$(".ws_switchbox").eq(0).find(".c_name");n.eq(0).attr("href","http://you.ctrip.com/place/"+e+GSDistrictId+".html");n.eq(1).attr("href","http://you.ctrip.com/sight/"+e+GSDistrictId+".html");if(void 0!==a.HotelData)if(null!=a.HotelData&&0<a.HotelData.Hotel.length){$(".hotel_wrap").show();
a=a.HotelData;e=$("#hotelTab");n=a.HotelTab;f=n.length;r=0;for(k=[];r<f;r++)h=n[r],0===r?k.push('<li class="current" data-id="'+h.Id+'"><span><a href="javascript:;">'+h.Name+"</a></span></li>"):k.push('<li data-id="'+h.Id+'"><span><a href="javascript:;">'+h.Name+"</a></span></li>");e.html(k.join(""));$("#hotelWrap").html($.tmpl($("#hotel_tpl").html(),a.Hotel))}else $(".hotel_wrap").hide();else $(".hotel_wrap").hide()});return!1});$(document).on("click",function(){$("#citySelect dd").removeClass("current");
$("#citySelect dt").removeClass("active")});$("#gs_operate_right_fix a.close").on("click",function(){$(this).parent().parent().hide()});$("#carpoolTab li").on("click",function(){var a=$(this);a.hasClass("current")||(a.addClass("current").siblings().removeClass("current"),a.attr("data-id"),a=a.index(),$("#carpoolWrap").find("ul").eq(a).addClass("current").siblings().removeClass("current"))});$("#SearchBtn").on("click",function(){var a=GS.ent()+"/SearchSite/?query=",b=$("#gsSearch").val()||"";"\u641c\u7d22\u57ce\u5e02\u3001\u666f\u70b9\u3001\u6e38\u8bb0\u3001\u95ee\u7b54\u3001\u7528\u6237"==
b&&(b="");""!=b&&(window.location.href=a+escape(b));return!1});$("#gsSearch").val("");$("#hotelTo").val("");$("#hotelKeyword").val("");$("#flightFrom").val("");$("#flightTo").val("");$("#travelFrom").val("");$("#travelTo").val("");$("#ticketText").val("");$("#gopagetext").val("");$(".ws_right .appbg_bottom").addClass("appbg_aup");var b,e={hideControlOnEnd:!0,infiniteLoop:!1,pager:!1,nextText:" ",prevText:" ",minSlides:3,maxSlides:3,slideWidth:159,slideMargin:1},k={hideControlOnEnd:!0,infiniteLoop:!1,
pager:!1,nextText:" ",prevText:" ",minSlides:3,maxSlides:3,slideWidth:226,slideMargin:1};b=980>=$(document).width?$(".special_topic_scroll").bxSlider(e):$(".special_topic_scroll").bxSlider(k);$(window).resize(function(){setTimeout(function(){980>=$(document).width?b.reloadSlider(e):b.reloadSlider(k)},200)})});
var GSDistrictId=INTERFACE.district,showLoading=function(b){$("javascript:void(0)"+b).html('<div class="gs_list_load"><div class="gs_loading_gay"></div></div>')},showNoData=function(b,e){e=e||"\u5f88\u62b1\u6b49\uff0c\u6682\u65f6\u65e0\u6cd5\u627e\u5230\u7b26\u5408\u8981\u6c42\u7684\u6570\u636e\u3002";$("javascript:void(0)"+b).html('<div class="gs_list_load"><i class="listface"></i>'+e+"</div>")};
$(function(){var b=1,e=function(){var a=$("#travelTab li.current").attr("data-id")||"",c=$("#travelWrap");showLoading("travelWrap");$("#pagerBox").html("");INTERFACE.getTravelData({travleType:a,pageIndex:b},function(a){a&&a.Travel&&0<a.Travel.length?c.html($.tmpl($("#travel_tpl").html(),a.Travel)):showNoData("travelWrap");a=a.Total;b=parseInt(b,10);var e=Math.ceil(a/10),k=10*(b-1)+1,m=10*b,h=1===b?!0:!1,v=b===e?!0:!1,f=1,p=5,r=[],n=0>=b-1?1:b-1,t=b+1>=e?e:b+1;5<e?5<=b&&b<=e-2?(f=b-2,p=b+2):b==e-1?
(f=b-2-1,p=e):b==e&&(f=e-4,p=e):p=e;for(;f<=p;f++)r.push(f);a={PageIndex:b,Start:k,End:m,Total:a,IsFirstPage:h,IsEndPage:v,PageArray:r,TotalPage:e,PrevPage:n,NextPage:t};$("#pagerBox").html($.tmpl($("#pager_tpl").html(),a));$.pageEventBind()})},k=function(a){b=a||1;e();a=$(".journal_wrap").offset().top;$("body,html").animate({scrollTop:a},500)};$("#wisdomTourismTab li").on("click",function(){var a=$(this);if(!a.hasClass("current")){a.addClass("current").siblings().removeClass("current");var a=a.attr("data-id")||
"",b=$("#wisdomTourismWrap");showLoading("wisdomTourismWrap");INTERFACE.getWisdomTourismData(a,function(a){a&&0<a.length?b.html($.tmpl($("#wisdom_tourism_tpl").html(),a)):showNoData("wisdomTourismWrap")})}});$("#hotelTab").on("click","li",function(){var a=$(this);if(!a.hasClass("current")){a.addClass("current").siblings().removeClass("current");var a=a.attr("data-id")||"",b=$("#hotelWrap");showLoading("hotelWrap");INTERFACE.getHotelData({id:a,districtId:GSDistrictId},function(a){a&&0<a.length?b.html($.tmpl($("#hotel_tpl").html(),
a)):showNoData("hotelWrap")})}});$("#travelTab li").on("click",function(){var a=$(this);a.hasClass("current")||(a.addClass("current").siblings().removeClass("current"),b=1,e())});$.pageLinkJump=function(a,b){k(a)};$("#pagerBox").on("click","a",function(){var a=$(this),b=1;a.hasClass("gopage")||a.hasClass("disabled")||(b=a.attr("data-page")||1,k(b));return!1})});
(function(b){var e={mode:"horizontal",slideSelector:"",infiniteLoop:!0,hideControlOnEnd:!1,speed:500,easing:null,slideMargin:0,startSlide:0,randomStart:!1,captions:!1,ticker:!1,tickerHover:!1,adaptiveHeight:!1,adaptiveHeightSpeed:500,video:!1,useCSS:!0,preloadImages:"visible",responsive:!0,touchEnabled:!0,swipeThreshold:50,oneToOneTouch:!0,preventDefaultSwipeX:!0,preventDefaultSwipeY:!1,pager:!0,pagerType:"full",pagerShortSeparator:" / ",pagerSelector:null,buildPager:null,pagerCustom:null,controls:!0,
nextText:"Next",prevText:"Prev",nextSelector:null,prevSelector:null,autoControls:!1,startText:"Start",stopText:"Stop",autoControlsCombine:!1,autoControlsSelector:null,auto:!1,pause:4E3,autoStart:!0,autoDirection:"next",autoHover:!1,autoDelay:0,minSlides:1,maxSlides:1,moveSlides:0,slideWidth:0,onSliderLoad:function(){},onSlideBefore:function(){},onSlideAfter:function(){},onSlideNext:function(){},onSlidePrev:function(){}};b.fn.bxSlider=function(k){if(0==this.length)return this;if(1<this.length)return this.each(function(){b(this).bxSlider(k)}),
this;var a={},c=this,d=b(window).width(),g=b(window).height(),w=function(){a.settings=b.extend({},e,k);a.settings.slideWidth=parseInt(a.settings.slideWidth);a.children=c.children(a.settings.slideSelector);a.children.length<a.settings.minSlides&&(a.settings.minSlides=a.children.length);a.children.length<a.settings.maxSlides&&(a.settings.maxSlides=a.children.length);a.settings.randomStart&&(a.settings.startSlide=Math.floor(Math.random()*a.children.length));a.active={index:a.settings.startSlide};a.carousel=
1<a.settings.minSlides||1<a.settings.maxSlides;a.carousel&&(a.settings.preloadImages="all");a.minThreshold=a.settings.minSlides*a.settings.slideWidth+(a.settings.minSlides-1)*a.settings.slideMargin;a.maxThreshold=a.settings.maxSlides*a.settings.slideWidth+(a.settings.maxSlides-1)*a.settings.slideMargin;a.working=!1;a.controls={};a.interval=null;a.animProp="vertical"==a.settings.mode?"top":"left";a.usingCSS=a.settings.useCSS&&"fade"!=a.settings.mode&&function(){var b=document.createElement("div"),
c=["WebkitPerspective","MozPerspective","OPerspective","msPerspective"],d;for(d in c)if(void 0!==b.style[c[d]])return a.cssPrefix=c[d].replace("Perspective","").toLowerCase(),a.animProp="-"+a.cssPrefix+"-transform",!0;return!1}();"vertical"==a.settings.mode&&(a.settings.maxSlides=a.settings.minSlides);c.data("origStyle",c.attr("style"));c.children(a.settings.slideSelector).each(function(){b(this).data("origStyle",b(this).attr("style"))});m()},m=function(){c.wrap('<div class="bx-wrapper"><div class="bx-viewport"></div></div>');
a.viewport=c.parent();a.loader=b('<div class="bx-loading" />');a.viewport.prepend(a.loader);c.css({width:"horizontal"==a.settings.mode?100*a.children.length+215+"%":"auto",position:"relative"});a.usingCSS&&a.settings.easing?c.css("-"+a.cssPrefix+"-transition-timing-function",a.settings.easing):a.settings.easing||(a.settings.easing="swing");n();a.viewport.css({width:"100%",overflow:"hidden",position:"relative"});a.viewport.parent().css({maxWidth:p()});a.settings.pager||a.viewport.parent().css({margin:"0 auto 0px"});
a.children.css({"float":"horizontal"==a.settings.mode?"left":"none",listStyle:"none",position:"relative"});a.children.css("width",r());"horizontal"==a.settings.mode&&0<a.settings.slideMargin&&a.children.css("marginRight",a.settings.slideMargin);"vertical"==a.settings.mode&&0<a.settings.slideMargin&&a.children.css("marginBottom",a.settings.slideMargin);"fade"==a.settings.mode&&(a.children.css({position:"absolute",zIndex:0,display:"none"}),a.children.eq(a.settings.startSlide).css({zIndex:50,display:"block"}));
a.controls.el=b('<div class="bx-controls" />');a.settings.captions&&B();a.active.last=a.settings.startSlide==t()-1;a.settings.video&&c.fitVids();var z=a.children.eq(a.settings.startSlide);"all"==a.settings.preloadImages&&(z=a.children);a.settings.ticker?a.settings.pager=!1:(a.settings.pager&&(a.settings.pagerCustom?a.pagerEl=b(a.settings.pagerCustom):(a.pagerEl=b('<div class="bx-pager" />'),a.settings.pagerSelector?b(a.settings.pagerSelector).html(a.pagerEl):a.controls.el.addClass("bx-has-pager").append(a.pagerEl),
D()),a.pagerEl.delegate("a","click",L)),a.settings.controls&&(a.controls.next=b('<a class="bx-next" href="">'+a.settings.nextText+"</a>"),a.controls.prev=b('<a class="bx-prev" href="">'+a.settings.prevText+"</a>"),a.controls.next.bind("click",y),a.controls.prev.bind("click",C),a.settings.nextSelector&&b(a.settings.nextSelector).append(a.controls.next),a.settings.prevSelector&&b(a.settings.prevSelector).append(a.controls.prev),a.settings.nextSelector||a.settings.prevSelector||(a.controls.directionEl=
b('<div class="bx-controls-direction" />'),a.controls.directionEl.append(a.controls.prev).append(a.controls.next),a.controls.el.addClass("bx-has-controls-direction").append(a.controls.directionEl))),a.settings.auto&&a.settings.autoControls&&(a.controls.start=b('<div class="bx-controls-auto-item"><a class="bx-start" href="">'+a.settings.startText+"</a></div>"),a.controls.stop=b('<div class="bx-controls-auto-item"><a class="bx-stop" href="">'+a.settings.stopText+"</a></div>"),a.controls.autoEl=b('<div class="bx-controls-auto" />'),
a.controls.autoEl.delegate(".bx-start","click",x),a.controls.autoEl.delegate(".bx-stop","click",q),a.settings.autoControlsCombine?a.controls.autoEl.append(a.controls.start):a.controls.autoEl.append(a.controls.start).append(a.controls.stop),a.settings.autoControlsSelector?b(a.settings.autoControlsSelector).html(a.controls.autoEl):a.controls.el.addClass("bx-has-controls-auto").append(a.controls.autoEl),G(a.settings.autoStart?"stop":"start")),(a.settings.controls||a.settings.autoControls||a.settings.pager)&&
a.viewport.after(a.controls.el));h(z,v)},h=function(a,c){var d=a.find("img, iframe").length;if(0==d)c();else{var e=0;a.find("img, iframe").each(function(){b(this).one("load",function(){++e==d&&c()}).each(function(){this.complete&&b(this).load()})})}},v=function(){if(a.settings.infiniteLoop&&"fade"!=a.settings.mode&&!a.settings.ticker){var d="vertical"==a.settings.mode?a.settings.minSlides:a.settings.maxSlides,e=a.children.slice(0,d).clone().addClass("bx-clone"),d=a.children.slice(-d).clone().addClass("bx-clone");
c.append(e).prepend(d)}a.loader.remove();A();"vertical"==a.settings.mode&&(a.settings.adaptiveHeight=!0);a.viewport.height(f());c.redrawSlider();a.settings.onSliderLoad(a.active.index);a.initialized=!0;a.settings.responsive&&b(window).bind("resize",J);a.settings.auto&&a.settings.autoStart&&M();a.settings.ticker&&N();a.settings.pager&&l(a.settings.startSlide);a.settings.controls&&H();a.settings.touchEnabled&&!a.settings.ticker&&(a.touch={start:{x:0,y:0},end:{x:0,y:0}},a.viewport.bind("touchstart",
O))},f=function(){var c=0,d=b();if("vertical"==a.settings.mode||a.settings.adaptiveHeight)if(a.carousel){var e=1==a.settings.moveSlides?a.active.index:a.active.index*u(),d=a.children.eq(e);for(i=1;i<=a.settings.maxSlides-1;i++)d=e+i>=a.children.length?d.add(a.children.eq(i-1)):d.add(a.children.eq(e+i))}else d=a.children.eq(a.active.index);else d=a.children;"vertical"==a.settings.mode?(d.each(function(a){c+=b(this).outerHeight()}),0<a.settings.slideMargin&&(c+=a.settings.slideMargin*(a.settings.minSlides-
1))):c=Math.max.apply(Math,d.map(function(){return b(this).outerHeight(!1)}).get());return c},p=function(){var b="100%";0<a.settings.slideWidth&&(b="horizontal"==a.settings.mode?a.settings.maxSlides*a.settings.slideWidth+(a.settings.maxSlides-1)*a.settings.slideMargin:a.settings.slideWidth);return b},r=function(){var b=a.settings.slideWidth,c=a.viewport.width();0==a.settings.slideWidth||a.settings.slideWidth>c&&!a.carousel||"vertical"==a.settings.mode?b=c:1<a.settings.maxSlides&&"horizontal"==a.settings.mode&&
!(c>a.maxThreshold)&&c<a.minThreshold&&(b=(c-a.settings.slideMargin*(a.settings.minSlides-1))/a.settings.minSlides);return b},n=function(){var b=1;"horizontal"==a.settings.mode&&0<a.settings.slideWidth?a.viewport.width()<a.minThreshold?b=a.settings.minSlides:a.viewport.width()>a.maxThreshold?b=a.settings.maxSlides:(b=a.children.first().width(),b=Math.floor(a.viewport.width()/b)):"vertical"==a.settings.mode&&(b=a.settings.minSlides);return b},t=function(){var b=0;if(0<a.settings.moveSlides)if(a.settings.infiniteLoop)b=
a.children.length/u();else for(var c=0,d=0;c<a.children.length;)++b,c=d+n(),d+=a.settings.moveSlides<=n()?a.settings.moveSlides:n();else b=Math.ceil(a.children.length/n());return b},u=function(){return 0<a.settings.moveSlides&&a.settings.moveSlides<=n()?a.settings.moveSlides:n()},A=function(){if(a.children.length>a.settings.maxSlides&&a.active.last&&!a.settings.infiniteLoop)if("horizontal"==a.settings.mode){var b=a.children.last(),c=b.position();s(-(c.left-(a.viewport.width()-b.width())),"reset",
0)}else"vertical"==a.settings.mode&&(c=a.children.eq(a.children.length-a.settings.minSlides).position(),s(-c.top,"reset",0));else c=a.children.eq(a.active.index*u()).position(),a.active.index==t()-1&&(a.active.last=!0),void 0!=c&&("horizontal"==a.settings.mode?s(-c.left,"reset",0):"vertical"==a.settings.mode&&s(-c.top,"reset",0))},s=function(b,d,e,f){if(a.usingCSS)b="vertical"==a.settings.mode?"translate3d(0, "+b+"px, 0)":"translate3d("+b+"px, 0, 0)",c.css("-"+a.cssPrefix+"-transition-duration",e/
1E3+"s"),"slide"==d?(c.css(a.animProp,b),c.bind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){c.unbind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd");F()})):"reset"==d?c.css(a.animProp,b):"ticker"==d&&(c.css("-"+a.cssPrefix+"-transition-timing-function","linear"),c.css(a.animProp,b),c.bind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){c.unbind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd");s(f.resetValue,
"reset",0);E()}));else{var g={};g[a.animProp]=b;"slide"==d?c.animate(g,e,a.settings.easing,function(){F()}):"reset"==d?c.css(a.animProp,b):"ticker"==d&&c.animate(g,speed,"linear",function(){s(f.resetValue,"reset",0);E()})}},D=function(){for(var c="",d=t(),e=0;e<d;e++){var f="";a.settings.buildPager&&b.isFunction(a.settings.buildPager)?(f=a.settings.buildPager(e),a.pagerEl.addClass("bx-custom-pager")):(f=e+1,a.pagerEl.addClass("bx-default-pager"));c+='<div class="bx-pager-item"><a href="" data-slide-index="'+
e+'" class="bx-pager-link">'+f+"</a></div>"}a.pagerEl.html(c)},B=function(){a.children.each(function(a){a=b(this).find("img:first").attr("title");void 0!=a&&(""+a).length&&b(this).append('<div class="bx-caption"><span>'+a+"</span></div>")})},y=function(b){a.settings.auto&&c.stopAuto();c.goToNextSlide();b.preventDefault()},C=function(b){a.settings.auto&&c.stopAuto();c.goToPrevSlide();b.preventDefault()},x=function(a){c.startAuto();a.preventDefault()},q=function(a){c.stopAuto();a.preventDefault()},
L=function(d){a.settings.auto&&c.stopAuto();var e=b(d.currentTarget),e=parseInt(e.attr("data-slide-index"));e!=a.active.index&&c.goToSlide(e);d.preventDefault()},l=function(c){var d=a.children.length;"short"==a.settings.pagerType?(1<a.settings.maxSlides&&(d=Math.ceil(a.children.length/a.settings.maxSlides)),a.pagerEl.html(c+1+a.settings.pagerShortSeparator+d)):(a.pagerEl.find("a").removeClass("active"),a.pagerEl.each(function(a,d){b(d).find("a").eq(c).addClass("active")}))},F=function(){if(a.settings.infiniteLoop){var b=
"";0==a.active.index?b=a.children.eq(0).position():a.active.index==t()-1&&a.carousel?b=a.children.eq((t()-1)*u()).position():a.active.index==a.children.length-1&&(b=a.children.eq(a.children.length-1).position());"horizontal"==a.settings.mode?s(-b.left,"reset",0):"vertical"==a.settings.mode&&s(-b.top,"reset",0)}a.working=!1;a.settings.onSlideAfter(a.children.eq(a.active.index),a.oldIndex,a.active.index)},G=function(b){a.settings.autoControlsCombine?a.controls.autoEl.html(a.controls[b]):(a.controls.autoEl.find("a").removeClass("active"),
a.controls.autoEl.find("a:not(.bx-"+b+")").addClass("active"))},H=function(){1==t()?(a.controls.prev.addClass("disabled"),a.controls.next.addClass("disabled")):!a.settings.infiniteLoop&&a.settings.hideControlOnEnd&&(0==a.active.index?(a.controls.prev.addClass("disabled"),a.controls.next.removeClass("disabled")):a.active.index==t()-1?(a.controls.next.addClass("disabled"),a.controls.prev.removeClass("disabled")):(a.controls.prev.removeClass("disabled"),a.controls.next.removeClass("disabled")))},M=function(){0<
a.settings.autoDelay?setTimeout(c.startAuto,a.settings.autoDelay):c.startAuto();a.settings.autoHover&&c.hover(function(){a.interval&&(c.stopAuto(!0),a.autoPaused=!0)},function(){a.autoPaused&&(c.startAuto(!0),a.autoPaused=null)})},N=function(){var d=0;"next"==a.settings.autoDirection?c.append(a.children.clone().addClass("bx-clone")):(c.prepend(a.children.clone().addClass("bx-clone")),d=a.children.first().position(),d="horizontal"==a.settings.mode?-d.left:-d.top);s(d,"reset",0);a.settings.pager=!1;
a.settings.controls=!1;a.settings.autoControls=!1;a.settings.tickerHover&&!a.usingCSS&&a.viewport.hover(function(){c.stop()},function(){var d=0;a.children.each(function(c){d+="horizontal"==a.settings.mode?b(this).outerWidth(!0):b(this).outerHeight(!0)});var e=a.settings.speed/d*(d-Math.abs(parseInt(c.css("horizontal"==a.settings.mode?"left":"top"))));E(e)});E()},E=function(b){speed=b?b:a.settings.speed;b={left:0,top:0};var d={left:0,top:0};"next"==a.settings.autoDirection?b=c.find(".bx-clone").first().position():
d=a.children.first().position();s("horizontal"==a.settings.mode?-b.left:-b.top,"ticker",speed,{resetValue:"horizontal"==a.settings.mode?-d.left:-d.top})},O=function(b){a.working?b.preventDefault():(a.touch.originalPos=c.position(),b=b.originalEvent,a.touch.start.x=b.changedTouches[0].pageX,a.touch.start.y=b.changedTouches[0].pageY,a.viewport.bind("touchmove",I),a.viewport.bind("touchend",K))},I=function(b){var c=b.originalEvent,d=Math.abs(c.changedTouches[0].pageX-a.touch.start.x),e=Math.abs(c.changedTouches[0].pageY-
a.touch.start.y);3*d>e&&a.settings.preventDefaultSwipeX?b.preventDefault():3*e>d&&a.settings.preventDefaultSwipeY&&b.preventDefault();"fade"!=a.settings.mode&&a.settings.oneToOneTouch&&(b=0,"horizontal"==a.settings.mode?(c=c.changedTouches[0].pageX-a.touch.start.x,b=a.touch.originalPos.left+c):(c=c.changedTouches[0].pageY-a.touch.start.y,b=a.touch.originalPos.top+c),s(b,"reset",0))},K=function(b){a.viewport.unbind("touchmove",I);var d=b.originalEvent;b=0;a.touch.end.x=d.changedTouches[0].pageX;a.touch.end.y=
d.changedTouches[0].pageY;"fade"==a.settings.mode?(d=Math.abs(a.touch.start.x-a.touch.end.x),d>=a.settings.swipeThreshold&&(a.touch.start.x>a.touch.end.x?c.goToNextSlide():c.goToPrevSlide(),c.stopAuto())):("horizontal"==a.settings.mode?(d=a.touch.end.x-a.touch.start.x,b=a.touch.originalPos.left):(d=a.touch.end.y-a.touch.start.y,b=a.touch.originalPos.top),!a.settings.infiniteLoop&&(0==a.active.index&&0<d||a.active.last&&0>d)?s(b,"reset",200):Math.abs(d)>=a.settings.swipeThreshold?(0>d?c.goToNextSlide():
c.goToPrevSlide(),c.stopAuto()):s(b,"reset",200));a.viewport.unbind("touchend",K)},J=function(a){a=b(window).width();var e=b(window).height();if(d!=a||g!=e)d=a,g=e,c.redrawSlider()};c.goToSlide=function(d,e){if(!a.working&&a.active.index!=d){a.working=!0;a.oldIndex=a.active.index;0>d?a.active.index=t()-1:d>=t()?a.active.index=0:a.active.index=d;a.settings.onSlideBefore(a.children.eq(a.active.index),a.oldIndex,a.active.index);if("next"==e)a.settings.onSlideNext(a.children.eq(a.active.index),a.oldIndex,
a.active.index);else if("prev"==e)a.settings.onSlidePrev(a.children.eq(a.active.index),a.oldIndex,a.active.index);a.active.last=a.active.index>=t()-1;a.settings.pager&&l(a.active.index);a.settings.controls&&H();if("fade"==a.settings.mode)a.settings.adaptiveHeight&&a.viewport.height()!=f()&&a.viewport.animate({height:f()},a.settings.adaptiveHeightSpeed),a.children.filter(":visible").fadeOut(a.settings.speed).css({zIndex:0}),a.children.eq(a.active.index).css("zIndex",51).fadeIn(a.settings.speed,function(){b(this).css("zIndex",
50);F()});else{a.settings.adaptiveHeight&&a.viewport.height()!=f()&&a.viewport.animate({height:f()},a.settings.adaptiveHeightSpeed);var g=0,h={left:0,top:0};if(!a.settings.infiniteLoop&&a.carousel&&a.active.last)if("horizontal"==a.settings.mode)var k=a.children.eq(a.children.length-1),h=k.position(),g=a.viewport.width()-k.outerWidth();else h=a.children.eq(a.children.length-a.settings.minSlides).position();else a.carousel&&a.active.last&&"prev"==e?(h=1==a.settings.moveSlides?a.settings.maxSlides-u():
(t()-1)*u()-(a.children.length-a.settings.maxSlides),k=c.children(".bx-clone").eq(h),h=k.position()):"next"==e&&0==a.active.index?(h=c.find("> .bx-clone").eq(a.settings.maxSlides).position(),a.active.last=!1):0<=d&&(h=d*u(),h=a.children.eq(h).position());"undefined"!==typeof h&&s("horizontal"==a.settings.mode?-(h.left-g):-h.top,"slide",a.settings.speed)}}};c.goToNextSlide=function(){if(a.settings.infiniteLoop||!a.active.last){var b=parseInt(a.active.index)+1;c.goToSlide(b,"next")}};c.goToPrevSlide=
function(){if(a.settings.infiniteLoop||0!=a.active.index){var b=parseInt(a.active.index)-1;c.goToSlide(b,"prev")}};c.startAuto=function(b){a.interval||(a.interval=setInterval(function(){"next"==a.settings.autoDirection?c.goToNextSlide():c.goToPrevSlide()},a.settings.pause),a.settings.autoControls&&!0!=b&&G("stop"))};c.stopAuto=function(b){a.interval&&(clearInterval(a.interval),a.interval=null,a.settings.autoControls&&!0!=b&&G("start"))};c.getCurrentSlide=function(){return a.active.index};c.getSlideCount=
function(){return a.children.length};c.redrawSlider=function(){a.children.add(c.find(".bx-clone")).outerWidth(r());a.viewport.css("height",f());a.settings.ticker||A();a.active.last&&(a.active.index=t()-1);a.active.index>=t()&&(a.active.last=!0);a.settings.pager&&!a.settings.pagerCustom&&(D(),l(a.active.index))};c.destroySlider=function(){a.initialized&&(a.initialized=!1,b(".bx-clone",this).remove(),a.children.each(function(){void 0!=b(this).data("origStyle")?b(this).attr("style",b(this).data("origStyle")):
b(this).removeAttr("style")}),void 0!=b(this).data("origStyle")?this.attr("style",b(this).data("origStyle")):b(this).removeAttr("style"),b(this).unwrap().unwrap(),a.controls.el&&a.controls.el.remove(),a.controls.next&&a.controls.next.remove(),a.controls.prev&&a.controls.prev.remove(),a.pagerEl&&a.pagerEl.remove(),b(".bx-caption",this).remove(),a.controls.autoEl&&a.controls.autoEl.remove(),clearInterval(a.interval),a.settings.responsive&&b(window).unbind("resize",J))};c.reloadSlider=function(a){void 0!=
a&&(k=a);c.destroySlider();w()};w();return this}})(jQuery);
