/* 2015-03-10 14:40:52 r_zou */
$(function(){function c(){$("#asktop_ssinput").placeholder();$("body").append('<div id="asktitle_sspop" class="asktitle_sspop"><div class="sspop_ajax"></div><div class="sspop_tag cf"></div><a class="sspop_blink" title="" href="javascript:;" target="_blank">\u641c\u7d22\u66f4\u591a\u5173\u4e8e\u201c<b></b>\u201d<i class="icon_rightarrow"></i></a></div>');$("#asktop_ssinput").keyup(function(a){0<=$(this).val().indexOf("<script>")&&$(this).val($(this).val().replace(/<script>/g,"\uff1cscript\uff1e"));
var b=$("#asktitle_sspop");$(this);var e=$(this).val(),c=ASKSEARCH_API.AskSiteLink+"?keywords="+encodeURIComponent(e);b.find(".sspop_blink").find("b").html(e);b.find(".sspop_blink").attr("title","\u641c\u7d22\u66f4\u591a\u5173\u4e8e\u201c"+e+"\u201d");b.find(".sspop_blink").attr({href:c});if(""!=$.trim(e))switch(a.keyCode){case 40:b.find(".current").index()==b.find(".sspop_ajax").find("a").length-1?(a=b.find(".current"),a.removeClass("current"),b.find("a").eq(0).addClass("current")):0<b.find(".current").length?
(a=b.find(".current"),a.next("a").addClass("current"),a.removeClass("current")):b.find("a").eq(0).addClass("current");break;case 38:b.find(".current").hasClass("sspop_blink")?(a=b.find(".current"),b.find("a").eq(b.find(".sspop_ajax").find("a").length-1).addClass("current"),a.removeClass("current")):0==b.find(".current").index()?b.find(".current").removeClass("current"):0<b.find(".current").length&&(a=b.find(".current"),a.prev("a").addClass("current"),a.removeClass("current"));break;case 13:a=0<b.find(".current").length?
b.find(".current").attr("href"):ASKSEARCH_API.AskSiteLink+"?keywords="+encodeURIComponent(e);window.location.href=a;break;case 27:b.fadeOut(300);break;default:clearTimeout(f),f=setTimeout(function(){if(d[e]){var a=$("#asktop_ssinput").offset();b.css({top:a.top+40,left:a.left}).fadeIn(300);b.find(".sspop_ajax").html("");a="";for(i=0;i<d[e].Asks.length;i++)a=a+'<a target="_blank" title="'+d[e].Asks[i].HighlighterTitle+'" href="'+d[e].Asks[i].AskLinkUrl+'"><span class="asktitle">'+d[e].Asks[i].AskTitle+
'</span><span class="answernum">'+d[e].Asks[i].ReplyCount+"\u56de\u7b54</span></a>";b.find(".sspop_ajax").html(a);if(null!=d[e].MatchTags){a='<span class="lefttitle">\u76f8\u5173\u8bdd\u9898</span>';b.find(".sspop_tag").html("");for(i=0;i<d[e].MatchTags.length;i++)a=a+'<a class="asktag_item" target="_blank" title="'+d[e].MatchTags[i].TagName+'" href="'+d[e].TagAggregateLink+'"><span>'+d[e].MatchTags[i].TagName+"</span></a>";b.find(".sspop_tag").show().html(a)}else b.find(".sspop_tag").hide()}else $.getJSON(ASKSEARCH_API.GetAskSearch+
"&Jsoncallback=?",{Keyword:encodeURIComponent(e)},function(a){if(void 0!=a){var c=$("#asktop_ssinput").offset();b.css({top:c.top+40,left:c.left}).fadeIn(300);b.find(".sspop_ajax").html("");c="";for(i=0;i<a.Asks.length;i++)c=c+'<a target="_blank" title="'+a.Asks[i].HighlighterTitle+'" href="'+a.Asks[i].AskLinkUrl+'"><span class="asktitle">'+a.Asks[i].AskTitle+'</span><span class="answernum">'+a.Asks[i].ReplyCount+"\u56de\u7b54</span></a>";b.find(".sspop_ajax").html(c);if(null!=a.MatchTags){c='<span class="lefttitle">\u76f8\u5173\u8bdd\u9898</span>';
b.find(".sspop_tag").html("");for(i=0;i<a.MatchTags.length;i++)c=c+'<a class="asktag_item" target="_blank" title="'+a.MatchTags[i].TagName+'" href="'+a.TagAggregateLink+'"><span>'+a.MatchTags[i].TagName+"</span></a>";b.find(".sspop_tag").show().html(c)}else b.find(".sspop_tag").hide();d[e]={};d[e]=a}else b.find(".sspop_ajax").html(""),b.find(".sspop_tag").html(""),b.fadeOut(300)})},200)}else clearTimeout(f),b.fadeOut(300)})}var f=0,d={};0<$("#asktop_ssinput").length&&c();$(".asksearch .askss_button").click(function(){var a=
$("#asktop_ssinput").val();if(""==a.replace(/(^\s*)|(\s*$)/g,"")||"\u63d0\u95ee\u524d\u4e0d\u59a8\u5148\u641c\u7d22\u4e0b\uff0c\u770b\u770b\u4f60\u7684\u95ee\u9898\u662f\u5426\u5df2\u7ecf\u6709\u4eba\u8be2\u95ee\u8fc7"==a)return!1;a=ASKSEARCH_API.AskSiteLink+"?keywords="+encodeURIComponent(a);window.location.href=a});$(".abouttdd").on("click",".abouttdd ul li h3",function(){$this=$(this);$this.addClass("cur");$this.parent("li").siblings("li").find("h3").removeClass("cur");$this.siblings(".abouttdd_licon").slideDown(300);
$this.parent("li").siblings("li").find(".abouttdd_licon").slideUp(300)});$(".abouttdd").on("click",".tddcitytab_t a",function(){$(this).addClass("on").siblings().removeClass("on");$(this).parent().siblings(".tddcitytab_c").hide();$(this).parent().siblings(".tddcitytab_c").eq($(this).index()).fadeIn(300)});$("body").on("mouseenter",".asklist li",function(){$(this).addClass("on");$(this).find(".asktag_item").addClass("listhover")}).on("mouseleave",".asklist li",function(){$(this).removeClass("on");
$(this).find(".asktag_item").removeClass("listhover")}).on("click",".asklist li,.asklist .asktag_item,.asklist .ask_user",function(){window.open($(this).attr("data-href"));return!1});$.pageLinkJump=function(a){a=$(".pager_v1 input").val();askpageJump({pageNum:a})}});
(function(c){c.pageEventBind=function(){function f(a){""==a||a>d?b():c.pageLinkJump&&c.pageLinkJump()}var d=parseInt(c(".pager_v1").find(".numpage").text()),a=c(".pager_v1").find("span input"),b=function(){var b=a.clone(),c=a.offset(),d=0;a.css("visibility","hidden");b.css({position:"absolute",top:c.top+"px",left:c.left+"px",width:"18px",height:"16px",border:"1px solid #ccc"}).appendTo("body");var f=setInterval(function(){d++;b.css({top:c.top+2*Math.sin(d)+"px",left:c.left+1*Math.cos(d)+"px"});15==
d&&(clearInterval(f),a.css("visibility","visible"),b.remove())},30)};a.keyup(function(a){var b=c(this).val();/\D/g.test(b)&&c(this).val("");13==a.keyCode&&f(b)}).parent("span").siblings(".gopage").click(function(){var b=a.val();f(b)})};c.pageEventBind()})(jQuery);
